### ISSUE TITLE
Save coins from Numismatic Overhaul in graves

### ISSUE THREAD

**Issue by Landrozaum** [B1n-ry/Youre-in-grave-danger#100]
**Is your feature request related to a problem or do you just have an idea that fit the theme of the mod? Please describe.**
Is bad when i die with [Numismatic Overhaul](https://modrinth.com/mod/numismatic-overhaul) installed and my coins just fall in the ground, so i can lose them if i die in lava.

**Describe the solution you'd like**
Add a feature that saves the [Numismatic Overhaul](https://modrinth.com/mod/numismatic-overhaul) coins. The coins are saved in the inventory but in a sepparate area created by NumsOverh mod itself, so when i die, all items from the Money Pouch falls in the ground, can you add this different inventory in the pools of saved items.

**Comment by B1n-ry** [comment]
Alright this shouldn't be too difficult. You can expect compat with numismatic overhaul in the next version of the mod

**Comment by B1n-ry** [comment]
Only took 3 months to get that version out! *sigh* I need to get back to modding more...
Anyway numismatic overhaul has compat with the graves between versions 1.18.2 to 1.19.4 now. Let me know if there's anything else that seem odd or should be in the mod!
