### ISSUE TITLE
Create mod contraptions will void contents of grave

### ISSUE THREAD

**Issue by MissPotato** [B1n-ry/Youre-in-grave-danger#101]
**Describe the bug**
If a create contraption stops on top of the grave the contents of the grave will be destroyed and a decorative grave will be dropped instead.

**To Reproduce**
1. Create this contraption https://i.imgur.com/PwnB7t0.png (see below for better explanation)
2. Right click the mechanic bearing to get it to spin
3. Die where the contraption started to spawn a grave
4. Right click the mechanic bearing
5. Grave gets broken voiding items

Pink is a _water wheel_ and a _shaft,_ which is connected to green which is a _mechanic bearing_ facing up to the sky, blue is a a set of _linear chassis_ laid horizontally. The bits on the end aren't necessary to reproduce.

**Expected behavior**
As a fall back, anytime a grave is destroyed in a non-handled way maybe drop items to the ground? Seems like a nightmare to solve any other way.

**Desktop (please complete the following information):**
 - OS: Linux Cent OS server
 - Minecraft Version: Fabric 1.19.2
 - Version: 1.4.6
 - Create: v0.5.0g-796

**Comment by B1n-ry** [comment]
The thing with graves being removed unhandled is quite a delicate issue. The thing is that it's quite tricky to make out when the player retrieves a grave and it's destroyed by other means. I can try to get something in place that will drop items, or just prevent graves from being destroyed from create contraptions, but I can't make any promises. If graves do disappear I do have a backup system in place you can access through `/yigd` commands. If you're OP you should have no trouble getting the items back. But unfortunately there's not anything else than the commands at the moment that will help in this situation

**Comment by MissPotato** [comment]
Yeah, I figured this would be a nightmare to deal with. On one hand, the "fail safe" above would be a lot easier than handling every exception. On the other hand, probably opens up a whole list of dupe bugs. Heck, even with the create example, without special cases specifically for Create - which is what my suggestion was trying to avoid - how would you know if a create contraption destroyed the grave or just merged the grave with itself... Seems like I didn't bake that idea long enough.

 I was able to get an admin on to get my grave back. Super awesome that command exists for these kinds of situations!

**Comment by B1n-ry** [comment]
Sooo... It's been a while, but I've added a config that can change this. If you set `onDestroyedDrop` to `ITEM_CONTENTS` all the grave's items will drop when it disappears and has not been claimed. Could conflict with the grave timout thing that destroys the grave after some time, but I haven't tested it yet. You can also set the config to `GRAVE_BLOCK` making the grave block drop. Placing the grave block again will have all its contents remaining, and can be claimed again.
Sorry for taking so long, but now I've updated the mod. Hope this will work for you. Didn't test with create contraptions as I basically know nothing about the progression or mechanics of the mod, so I wouldn't know where to start testing, but it *should* work
