### ISSUE TITLE
Crash on ModMenu open

### ISSUE THREAD

**Issue by Kai-mbe** [B1n-ry/Youre-in-grave-danger#102]
Hi,
I'm getting a crash when opening Modmenu. Seems to only happen after a while in the world.
Noticed yigd in the logs along with a few mods by XanderIsDev.

> [22:06:47] [Render thread/ERROR]: Error from mod 'yigd'
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129

It's a kitchen sink pack so probably just an incompatibility, but wanted to see if you had any ideas.

Thanks.

[latest.log](https://github.com/B1n-ry/Youre-in-grave-danger/files/10775205/latest.log)

**Comment by B1n-ry** [comment]
Sorry for not replying sooner, I've not really felt like modding lately. I believe I can be of assistance now however. I realize this was reported 3 weeks ago now, but are you still having problems with this? Looks like the config file might be broken or something. If you've not initially changed anything in the yigd configs, you can try to just delete the yigd.toml file and let it regenerate. Do let me know if you still want help if there's anything I can do

**Comment by Kai-mbe** [comment]
Hi,
It was solved by downgrading YetAnotherConfigLib as suggested by isXander (https://github.com/isXander/Zoomify/issues/122). Sorry, should have updated sooner.

Thanks anyway, for the reply and my favorite grave mod.

**Comment by B1n-ry** [comment]
No worries. Glad you enjoy the mod, and thanks for letting me know you had fixed it!
