### ISSUE TITLE
mod kicking u from server when trying to restore grave with commands

### ISSUE THREAD

**Issue by S0apyy** [B1n-ry/Youre-in-grave-danger#103]
when i restore my or someone else's grave with the /yigd grave screen too much the server kicks me but my account would stay in the server until its either restarted or the my account times out.

i use the 1.19.2 1.4.8 version of the mod

the server i run is on windows 11 and my client is also on windows 11

**Comment by B1n-ry** [comment]
Server logs? I need to know more about what happens and why the server kicks you to act on this

**Comment by S0apyy** [comment]
@B1n-ry  these are the relevant log outputs
[logs.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/10798208/logs.txt)
when i clicked restore client side it looked like i was still in the server then the server tried to reconnect me succeeded but kicked me client side and i couldnt join again until i times out or server was restarted. couldn't be kicked aswell.

if you would like me to copy only the relevant parts of that text file i could

**Comment by B1n-ry** [comment]
Quite some time later, and I think this issue is fixed in the latest release I just dropped. If you still play and it's not fixed, let me know. Anyway thanks for reporting this in!
