### ISSUE TITLE
applicable

### ISSUE THREAD

**Issue by Salo110-cell** [B1n-ry/Youre-in-grave-danger#104]
**Describe the bug**
A somewhat clear description of what the bug is.

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS]
 - Minecraft Version: [e.g. 1.16.5, 1.17.1]
 - Version: [e.g. 1.0.0, 1.0.3]

**Additional context**

**Screenshots**

**Comment by B1n-ry** [comment]
Is there a problem you're experiencing? I don't understand what you mean with "applicable". Please fill out the bug report, and then I might be able to help

**Comment by lenrik1589** [comment]
This should be closed as invalid…

**Comment by B1n-ry** [comment]
fair enough. Just wanted to see if they actually had anything to report
