### ISSUE TITLE
End City Chest Loot Table (and possibly other ones as well) breaking with this mod

### ISSUE THREAD

**Issue by Sar4h-3** [B1n-ry/Youre-in-grave-danger#11]
**Describe the bug**
With this mod enabled, the end city loot table gets broken.
Instead of giving the loot when broken or interacted with, you*ll get a stack trace that (for me) doesn't seem to fit to this weird issue.

**To Reproduce**
- use setblock to place a Chest with the right loot table:   ```/setblock ~ ~1 ~
minecraft:chest{LootTable:"minecraft:chests/end_city_treasure"} ```
- break or interact with the newly placed chest (its a good idea to copy it with control + middle mouse button)
- if you interact with it, nothing will happen ingame, you'll just get an error in the console
- if you break it, nothing will drop and the same error will appear in the console

**Expected behavior**
The end loot will generate as normal without issues

**Versions**
 - OS: Win10
 - Minecraft Version: 1.18
 - Fabric Version: 0.12.8
 - Fabric API Version: 0.43.1
 - Mod Version: 1.2.3

**Additional context**
[Stack Trace i got while testing](https://github.com/B1n-ry/Youre-in-grave-danger/files/7653949/message.1.txt)

**Comment by B1n-ry** [comment]
Fixed in 1.1.11 for 1.17.1 and **1.2.5 for 1.18** (which I guess you are more interested in)
Thank you for using my mod and reporting this issue!
