### ISSUE TITLE
OP Players do not get graves

### ISSUE THREAD

**Issue by WardsParadox** [B1n-ry/Youre-in-grave-danger#117]
**Describe the bug**
OP players do not get graves generated.

**To Reproduce**
1. Load new world
2. Op player
3. Kill Op player
4. No grave spawns

**Expected behavior**
Grave to spawn

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.19.4
 - Version: 1.6.0

**Additional context**
Server Logs:

```
13.05 02:51:47 [Server] Server thread/INFO death.attack.player //niknakodile dying
13.05 02:51:47 [Server] Server thread/INFO Grave spawned at: -3865, 99, 735 | minecraft:overworld
13.05 02:52:04 [Server] Server thread/INFO Grave at -3865, 99, 735 was replaced with Block{minecraft:air}
13.05 02:52:04 [Server] Server thread/INFO niknakodile is retrieving their grave at -3865, 99, 735
13.05 02:52:04 [Server] Server thread/INFO niknakodile retrieved the items from the grave
13.05 02:54:20 [Server] Server thread/INFO death.attack.player // Me dying


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by WardsParadox** [comment]
This is outside of all spawn protection. No claims, etc.

**Comment by WardsParadox** [comment]
Ok, deopped my account, still not spawning grave for me. Seems like something's borked with my account.

**Comment by WardsParadox** [comment]
Hmmm after diving into settings and deleting the /world/data/yigd_grave_data.dat file, graves are now fully back up. I should have checked the file before doing that.

Any logs you need to figure out why this stopped working?

**Comment by B1n-ry** [comment]
Any logs would be what you already sent, if there was any error thrown in between. Doesn't look like it though, so the only idea I have is that either you or someone else blacklisted you from generating graves. There is a command called `/yigd whitelist` but by default it's a blacklist. You can toggle it with a command to a whitelist. It's for banning certain people or only allowing certain people graves

**Comment by WardsParadox** [comment]
Maybe. Only OP on server, but when I was trying to rescue someone's stuff from a dungeon in a panic, I must have entered that.
