### ISSUE TITLE
[Request] Keep xpDropPercent on death.

### ISSUE THREAD

**Issue by sisby-folk** [B1n-ry/Youre-in-grave-danger#118]
**Is your feature request related to a problem or do you just have an idea that fit the theme of the mod? Please describe.**
We maintain a modpack that uses waystones, which cost XP to use. Retrieving graves with YIGD is fun, but having to do something strange like "smelt an item" or "kill a mob" in order to get the paltry 7 xp required to use a warp to do so is strange and tedious.

**Describe the solution you'd like**
I'd love a toggle option - effectively a third setting for `putXpInGrave`, that gives the XP directly to the respawned player - according to whatever `xpDropPercent` is set to. That is to say - the XP always stays with the player and never drops, but does decrease on death.

**Describe alternatives you've considered**
While we're not sure we'd use it ourselves, It could be interesting to have two percentages - one that the player respawns with, and the other that stays in the grave. This could avoid the need for a "setting", rather just a number that's usually 0.

**Comment by B1n-ry** [comment]
I don't think there will be more "content" updates before 1.20 releases, and after that 1.20 will be the main focus. It will however feature something like this in that version. An option to have xp kept when dying that you respawn with

**Comment by sleepingdragoninn** [comment]
I think this is done via keepPercentage now right?

**Comment by B1n-ry** [comment]
Oh right yeah that's correct. Forgot to close some of the issues when updating. Should probably do so...
