### ISSUE TITLE
origin [shulker origin] don't keep inventory when dead in server env

### ISSUE THREAD

**Issue by QianFuv** [B1n-ry/Youre-in-grave-danger#123]
same to https://github.com/B1n-ry/Youre-in-grave-danger/issues/86

in the single world it works well but in server this feature don't work

fabric 1.18.2

**Comment by B1n-ry** [comment]
Does this issue persist in your server with only origins and yigd installed (and cloth config+fabric api since yigd depend on those, don't know if origins has any dependencies though)

**Comment by QianFuv** [comment]
i will test now (10min

**Comment by QianFuv** [comment]
not happened
( so crazy

**Comment by QianFuv** [comment]
> not happened
> ( so crazy

so may have some problems with orther mod?

**Comment by B1n-ry** [comment]
Probably some other mod, yes. If you could find which mod causes the issue you can filter out the mods with a "divide and conquer" sorting method with disabling/removing mods, this is the fastest way to find the culprit mod to my knowledge

**Comment by QianFuv** [comment]
I will . but not now
maybe tomrrow

**Comment by QianFuv** [comment]
hard work give me more time

**Comment by QianFuv** [comment]
I test today, may be some server-side mod let this error
I'll tell more details one more hour ( may be two hours

**Comment by QianFuv** [comment]
I won't be following up on this issue, but what is known is that the cause of this problem is not just grave and origin, but from my investigation it is likely to be related to traveler's backpack.

**Comment by B1n-ry** [comment]
Ok alright thanks anyway. We'll see if I am able to identify and fix the issue in the future. If I remember then I'll update here
