### ISSUE TITLE
Opened grave, items didn't drop 1.19.2

### ISSUE THREAD

**Issue by Nyxlen** [B1n-ry/Youre-in-grave-danger#126]
**Describe the bug**
I'm playing the BetterMC modpack on fabric, 1.19.2, and while in the Bumblezone dimension died from fall damage while on my way to recover items from a prior death. Due to an item from the twilight forest mod, I had kept my armor and tools and mostly just lost my backpack. When I went back to retrieve this second death a day later, I right clicked the grave to open it, and the grave disappeared. It dropped no items. When I used the command provided: /yigd grave, to check, it says it's still available and has my full inventory.

**To Reproduce**
I'm unsure how to reproduce this bug.

**Expected behavior**
I expected to retrieve my entire inventory when activating the grave. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.19.2
 - Version: 1.4.9

**Additional context**
None of my prior deaths had issues, nor the deaths that happened right before and after this one.

**Screenshots**

![](https://cdn.discordapp.com/attachments/683882876365963326/1135355993908318259/image.png)
![image](https://github.com/B1n-ry/Youre-in-grave-danger/assets/50123105/2dee98ad-4cdd-4773-8268-bd14b1920b33)

**Comment by B1n-ry** [comment]
Huh that's weird. It would be more likely that the grave status changed and the block *didn't* disappear (which I believe still should not be able to happen).
Anyway you can "claim" your grave remotely with commands. If you play on singleplayer, open to lan with cheats enabled, open the grave overview GUI, and then press the restore button. If you play on a server, ask a server operator to open your grave overview GUI and do the same. As long as the "restore" button is pressed your inventory should be restored, just as if you claimed the grave. This requires you to be online though

**Comment by Nyxlen** [comment]
Thank you, the restore button did work and I have all my items back now.
