### ISSUE TITLE
Falling out of the world in the end places a tombstone in a nearly inaccessible location.

### ISSUE THREAD

**Issue by Meganium97** [B1n-ry/Youre-in-grave-danger#130]
Is there a way to change that and if so, why is it the default to just have it floating above the void instead of on the nearest solid block?

**Comment by B1n-ry** [comment]
Finding the nearest solid block can be heavy on resources (depending on how far away the nearest solid block is). Also I think it makes sense to generate the grave as close to where you died as possible.
There is a config though that you can enable that will cause the grave to be generated at the last block you stood on. I would assume you'd be happy with this?
