### ISSUE TITLE
Missing Soulbound Enchantment lang key

### ISSUE THREAD

**Issue by Partonetrain** [B1n-ry/Youre-in-grave-danger#133]
The Soulbound enchantment is missing its lang key. (Using Fabric 1.20.1)
![image](https://github.com/B1n-ry/Youre-in-grave-danger/assets/19861808/73f5ef57-ae28-4675-939f-f04e9a16d3fd)
(the "placeable" tooltip is from Supplementaries, please ignore that)

P.S. using the lang key "enchantment.yigd.soulbound.desc" will allow mods like [Enchantment Descriptions](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions) use the description.

**Comment by B1n-ry** [comment]
I've pushed the translation keys with the proper translation to the github now. Might release a new update in a few days. Thanks for reporting! Let me know if there's anything else I can do

**Comment by B1n-ry** [comment]
Forgot to update here, but it's been fixed in latest release (2.0.0-beta.3)
