### ISSUE TITLE
Grave not spawning and or crashing server.

### ISSUE THREAD

**Issue by Zunwolf1896** [B1n-ry/Youre-in-grave-danger#136]
Just added the mod (was so excited it got updated, adore this mod) Went online to test. I was killed by another player several times, my grave never spawned. Server crashed when i was killed by a Zombie twice. 

Nothing showed in the logs. 

Crash 1: https://mclo.gs/n74k7wU

Crash 2: https://mclo.gs/M1EtkFi 

Fabric: 0.14.24
Fabric API: 0.91.0
YIGD: 2.0.0 beta 4

Config: 
`{
  "inventoryConfig": {
    "dropPlayerHead": false,
    "itemLoss": {
      "enabled": false,
      "affectStacks": false,
      "usePercentRange": true,
      "lossRangeFrom": 0,
      "lossRangeTo": 100,
      "percentChanceOfLoss": 50,
      "canLoseSoulbound": false
    },
    "vanishingEnchantments": [
      "minecraft:vanishing_curse"
    ],
    "soulboundEnchantments": [
      "yigd:soulbound"
    ],
    "loseSoulboundLevelOnDeath": true,
    "vanishingSlots": [],
    "soulboundSlots": [],
    "dropOnGroundSlots": []
  },
  "expConfig": {
    "dropBehaviour": "VANILLA",
    "dropPercentage": 50,
    "keepPercentage": 0
  },
  "graveConfig": {
    "enabled": true,
    "storeItems": true,
    "storeXp": true,
    "informGraveLocation": true,
    "requireItem": false,
    "requiredItem": "",
    "requireShovelToLoot": false,
    "retrieveMethods": {
      "onClick": true,
      "onBreak": false,
      "onSneak": false,
      "onStand": false
    },
    "mergeStacksOnRetrieve": true,
    "dropOnRetrieve": "IN_INVENTORY",
    "dropGraveBlock": true,
    "generateEmptyGraves": false,
    "overrideSpawnProtection": true,
    "claimPriority": "GRAVE",
    "graveRobbing": {
      "enabled": false,
      "onlyMurderer": false,
      "afterTime": 1,
      "timeUnit": "HOURS",
      "robPriority": "INVENTORY",
      "notifyWhenRobbed": true,
      "tellWhoRobbed": true
    },
    "graveTimeout": {
      "enabled": false,
      "afterTime": 30,
      "timeUnit": "HOURS",
      "dropContentsOnTimeout": false
    },
    "treatBindingCurse": true,
    "generateGraveInVoid": false,
    "lowestGraveY": 3,
    "generateOnlyWithinBorder": true,
    "ignoredDeathTypes": [],
    "unlockable": true,
    "randomSpawn": {
      "percentSpawnChance": 5,
      "spawnEntity": "minecraft:zombie",
      "spawnNbt": "{ArmorItems:[{},{},{},{id:\"minecraft:player_head\",tag:{SkullOwner:{Name:\"${name}\",Id:\"${uuid}\"}},Count:1b}]}"
    },
    "generateOnLastGroundPos": true,
    "generationMaxDistance": {
      "x": 5,
      "y": 5,
      "z": 5
    },
    "useSoftBlockWhitelist": false,
    "useStrictBlockBlacklist": true,
    "replaceOldWhenClaimed": true,
    "persistentGraves": {
      "enabled": false,
      "showDeathDay": true,
      "showDeathIrlTime": true,
      "useAmPm": true
    },
    "dimensionBlacklist": [],
    "blockUnderGrave": {
      "enabled": true,
      "blockInDimensions": [
        {
          "key": "minecraft:overworld",
          "value": "minecraft:cobblestone"
        },
        {
          "key": "minecraft:the_nether",
          "value": "minecraft:soul_soil"
        },
        {
          "key": "minecraft:the_end",
          "value": "minecraft:end_stone"
        },
        {
          "key": "misc",
          "value": "minecraft:dirt"
        }
      ],
      "generateOnProtectedLand": true
    },
    "sellOutOfflinePeople": false,
    "maxBackupsPerPerson": 25,
    "dropFromOldestWhenDeleted": true
  },
  "respawnConfig": {
    "respawnEffects": [],
    "respawnHealth": 20,
    "resetHunger": true,
    "respawnHunger": 20,
    "resetSaturation": true,
    "respawnSaturation": 20.0,
    "extraItemDrops": []
  },
  "compatConfig": {
    "standardDropRuleInClaim": "PUT_IN_GRAVE",
    "enableInventorioCompat": false,
    "defaultInventorioDropRule": "PUT_IN_GRAVE",
    "enableLevelzCompat": false,
    "defaultLevelzDropRule": "PUT_IN_GRAVE",
    "enableNumismaticOverhaulCompat": true,
    "defaultNumismaticDropRule": "PUT_IN_GRAVE",
    "enableOriginsInventoryCompat": true,
    "defaultOriginsDropRule": "PUT_IN_GRAVE",
    "enableTravelersBackpackCompat": true,
    "defaultTravelersBackpackDropRule": "PUT_IN_GRAVE",
    "enableTrinketsCompat": true,
    "defaultTrinketsDropRule": "PUT_IN_GRAVE"
  },
  "commandConfig": {
    "mainCommand": "yigd",
    "basePermissionLevel": 0,
    "viewLatestPermissionLevel": 0,
    "viewSelfPermissionLevel": 0,
    "viewUserPermissionLevel": 2,
    "viewAllPermissionLevel": 2,
    "restorePermissionLevel": 2,
    "robPermissionLevel": 2,
    "whitelistPermissionLevel": 3,
    "deletePermissionLevel": 3,
    "unlockPermissionLevel": 0
  },
  "graveRendering": {
    "useCustomFeatureRenderer": true,
    "useSkullRenderer": true,
    "useTextRenderer": true,
    "adaptRenderer": false,
    "useGlowingEffect": true,
    "glowingDistance": 15
  },
  "extraFeatures": {
    "customSoulboundEnchant": true,
    "deathSightEnchant": {
      "enabled": false,
      "range": 64.0,
      "targets": "PLAYER_GRAVES"
    },
    "graveKeys": {
      "enabled": false,
      "rebindable": true,
      "required": true,
      "receiveOnRespawn": true,
      "targeting": "PLAYER_GRAVE"
    },
    "deathScroll": {
      "enabled": false,
      "rebindable": false,
      "receiveOnRespawn": false,
      "clickFunction": "VIEW_CONTENTS"
    }
  }
}`

**Comment by B1n-ry** [comment]
I guess that's what I get for not really being bothered to test the last version. Anyway I've pushed a new release now, 2.0.0-beta.5, that will fix this issue. Should be live on a few minutes. (As of editing this, it's live now)
Thanks for letting me know about the issue, and do let me know if you find *anything* else worth reporting!
