### ISSUE TITLE
Crash 1.20.1

### ISSUE THREAD

**Issue by Mysterious-Wrangler** [B1n-ry/Youre-in-grave-danger#140]
1.20.1 server
fabric 0.15.1
Mod 2.0.0 beta 6

Crashed in the nether when looting my grave. items duped and the grave is still there when i come back to the server.

[crash-2023-12-29_12.32.03-server.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/13795721/crash-2023-12-29_12.32.03-server.txt)

**Comment by dark-swordsman** [comment]
Yeah I think it's the same as #138.

**Comment by B1n-ry** [comment]
Yes. Just downgrade travelers backpack 1 version and it should work until I update

**Comment by Mysterious-Wrangler** [comment]
Thanks, ill downgrade for now.

**Comment by B1n-ry** [comment]
It now works with latest version of travelers backpack on yigd 2.0.0-beta.7. Files has been pushed and approved on curseforge and modrinth alike
