### ISSUE TITLE
KeepInventory

### ISSUE THREAD

**Issue by Waterstation** [B1n-ry/Youre-in-grave-danger#143]
Me and my friends are playing on a server and we are trying to disable this mod because we can't override this mod with gamerule keepinventory. Is there a way to override this command? Because with keepinventory on, the player keeps the items and can dupe the inventory by right clicking the gravestone. Im not sure if this is the mod's intention or my fault. Please help. ty

**Comment by B1n-ry** [comment]
Are you using the latest version of the mod. It should have been fixed in that version

**Comment by Waterstation** [comment]
Yes, I believe this is the latest version included within the mudpack.
![image](https://github.com/B1n-ry/Youre-in-grave-danger/assets/68083394/34f2fe5a-b64b-4081-8388-991e6bba8586)

**Comment by B1n-ry** [comment]
The latest version is 2.0.0-beta.7. Update to that version and your problem will be fixed
