### ISSUE TITLE
server crashed when someone died and displayed this error

### ISSUE THREAD

**Issue by S0apyy** [B1n-ry/Youre-in-grave-danger#144]
[crash-2024-01-24_18.17.37-server.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/14042343/crash-2024-01-24_18.17.37-server.txt)
it in turn also deleted all old grave contents

Using 1.20.1 beta 6 version of the mod

**Comment by B1n-ry** [comment]
Update to 2.0.0-beta.7. That will fix it for you
It in turn should be way more forgiving if it would delete old grave contents (as the items are not deleted anymore, just hidden, and not given back when claiming normally)
