### ISSUE TITLE
Disable XP loss

### ISSUE THREAD

**Issue by SHSHYLO** [B1n-ry/Youre-in-grave-danger#147]
not sure how to do this. no matter what i put nothing works and xp is still lost
"expConfig": {
    "dropBehaviour": "VANILLA",
    "dropPercentage": 0,
    "keepPercentage": 100
  },

**Comment by B1n-ry** [comment]
I assume you want 100% of player XP to be stored in the grave? For this you have to change dropBehaviour to PERCENTAGE. When left on VANILLA, the vanilla xp drop rate will kick in (can't drop more than 100 xp points which roughly translates to level 7). 
Does this fix your problem or did I misinterpret your issue?

**Comment by B1n-ry** [comment]
It's been 24 hours and you have not responded, so I'll assume you managed to fix it, so I'll close the issue. If this did *not* fix your issue, let me know and I will have a more proper look at the issue at hand

**Comment by SHSHYLO** [comment]
> I assume you want 100% of player XP to be stored in the grave? For this you have to change dropBehaviour to PERCENTAGE. When left on VANILLA, the vanilla xp drop rate will kick in (can't drop more than 100 xp points which roughly translates to level 7). Does this fix your problem or did I misinterpret your issue?

Yeah this works thank you!!! Sorry for the late response, I've been working. Shouldn't this be said in the config or anywhere else?

**Comment by B1n-ry** [comment]
I mean it's mentioned on the [wiki](https://github.com/B1n-ry/Youre-in-grave-danger/wiki), but  yes I should probably have it mentioned in the config somehow
