### ISSUE TITLE
Graves generate on death with empty inventory

### ISSUE THREAD

**Issue by NiChrosia** [B1n-ry/Youre-in-grave-danger#15]
**Describe the bug**
A somewhat clear description of what the bug is.

When dying with an empty inventory, a grave generates anyway, despite being pointless.

**To Reproduce**

Open a new survival world, commit suicide, and observe the empty grave.

**Expected behavior**

A grave should not generate with no items.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, MacOS]
 - Minecraft Version: [e.g. 1.16.5, 1.17.1]
 - Version: [e.g. 1.0.0, 1.0.3]
 
 OS: (Arch) Linux
 Minecraft: 1.18.1
 Version: 1.2.8B 

**Additional context**

**Screenshots**

**Comment by B1n-ry** [comment]
I will include a config in the next update that will not create a grave when you die with an empty inventory and no xp. Thanks for requesting this feature!
I'll close this issue once I've implemented this and released the version

**Comment by B1n-ry** [comment]
Released a new version (1.2.9) which includes this feature. Go try it out if you want to
