### ISSUE TITLE
Suggestion: Curios compat

### ISSUE THREAD

**Issue by AnasterianSunstrider** [B1n-ry/Youre-in-grave-danger#150]
Yes, I know that it's for a different loader but with the Sinytra Connector mod it's possible to use this mod on 1.20.1 forge now, and since the gravestone mods for forge either don't store exp and place curios back into their proper slots, or they simply aren't updated to 1.20.1 I guess this is kind of my last hope. While I know that even if this gets considered it will not be a priority and that maybe the code doesn't even allow it, I thought I might try suggesting it anyways.

**Comment by TomBCosmos** [comment]
I came to this GitHub specifically to suggest this but you have already beat me too it. This would be so useful @B1n-ry ! :)

This grave mod is by far the best grave mod there is (I used to run Fabric servers with this mod all the time).

I now have a Forge server due various reasons and with Sinytra Connector, this mod can be used on Forge worlds.

However, Curious API (the Forge version of Trinkets essentially) is not supported. So, anything in the Curious slots like masks, backpacks, rings, necklaces... The lot, they all just drop on the ground on death and are often despawned or lost. This is also including mods that add onto Curious like the mod **Iron's Spells 'n Spellbooks** which adds an additional slot for a spell book within Curious.

It would be amazing if compatibility could be added with Curious API so they all stay in the grave and go straight back to the Curious slots when recovered.

I know making a Fabric mod compatible with a Forge mod via Sinytra would most likely be way more difficult than if it was on the same loader but would be so greatly appreciated!

I'm on 1.20.1 so hoping you can add it for at least this version and up :)

**Comment by evanbones** [comment]
+1 This would be an awesome feature, the mod otherwise works flawlessly out of the box on Forge using Connector. I bet a lot more people/modpacks will download this if a Forge (using Connector) version was compatible with Curios

**Comment by B1n-ry** [comment]
It's possible it might work if you're using accessories and the curios compat layer, but I do not intend to add curios compat to the fabric version of the mod. 
I did however just a few hours ago release a neoforge version of the mod. It is only for 1.21, but has compat with curios. I don't know if sinytra connector works between forge and neoforge, but if there's enough demand I'll packport to 1.20 neoforge too anyway. 
Sorry if this is not exactly what you're looking for, I don't have any plans on porting to forge too

**Comment by Mentaleak** [comment]
I just wanted to show support for this feature and the ability to mark those slots as soulbound
