### ISSUE TITLE
Graves not returning armor for specific players

### ISSUE THREAD

**Issue by rruy-dev** [B1n-ry/Youre-in-grave-danger#154]
Issue: On a Fabric Server w/ v2.0.0-beta.10, graves don't return armor for some specific players, but they get all other items back.
The graves of the players do no show them as having armor in /yigd grave [player].

Observations:
I personally witnessed this happen to one of the players affected.. 
They died with armor on, within an FTB Chunk claim, used /back to return to their death point, claimed their grave, then no longer had the armor.
This happens whenever they die, to any grave of their graves that they reclaim.

I did a bunch of testing on the server it occurred, in a Local Private Server, and in multiple different Singleplayer worlds, but I cannot reproduce the issue even having the same exact inventories as the players who died.

**Comment by B1n-ry** [comment]
They aren't putting curse of vanishing on all of their armor are they? I assume not...
Could you check their inventories through the GUI system, and untick the buttons for destroyed, kept, respectively dropped items? Let me know if the armor appears in that case, and which toggle makes them appear. I'll try to look into this when I get enough time, but testing this would probably help a lot if it gives results.
PS. If the players aren't online you can use the `/yigd moderate` command

**Comment by rruy-dev** [comment]
Yea, I've looked at all this while they were online right after it happened on a couple of occasions.
Their armor was not enchanted at all.
I witnessed it happen to them on a couple of occasions, they died with armor on, then no longer had it upon recovery.
It doesn't happen to many players at all, but only a specific few.
I can see the grave within /yigd grave [player], the rest of their items other than armor show up in the listing and recover properly, but in the grave listing it appears that they didn't have armor at all (nothing within the armor slots).

Some other things I didn't note previously... 
This occurred on Fantasy MC Fabric v2.6.0 and again while the modpack was was in v2.7.0, live on the server. 
The pack runs on MC 1.20.1.
The players affected don't seem to have died again since then, so hasn't happened in the latest version of the pack v2.7.1.
The pack still has yigd v2.0.0-beta.10, as there was no pack update since yigd v2.0.0-beta.11 was released.

Sorry for the late reply

**Comment by B1n-ry** [comment]
Did you untick the boxes to the right? There were still no armor in the slots when doing that?

**Comment by rruy-dev** [comment]
> Did you untick the boxes to the right? There were still no armor in the slots when doing that?

Yep, unticked all the boxes, ensured I was looking at the correct graves by identifying the coordinates of the graves, and made sure I was at the exact death point where the grave was generated,

**Comment by B1n-ry** [comment]
I would ask which modpack/collection of mods you're using, but I'm not sure that I'd be able to reproduce the issue. I could try though, so having a copy of your (or rather the player who this happened to)'s instance might help

**Comment by rruy-dev** [comment]
Yea.. I couldn't reproduce it personally, on the server it happened, with the exact items the players had.. From the armor that they were wearing and didn't receive back, to every item in the exact same slots of the inventory, at the exact death points they previously died.
It seems to only affect specific players, regardless of any other conditions.

I'll notify the pack dev of the latest release of the mod, and test with the affected players if the issue continues to happen. Since reproducing it seems impossible for unaffected players.
I'll try to capture video of the issue too

**Comment by B1n-ry** [comment]
I don't think video would help much tbh. The only thing I can think of currently that would put players aside from other ones would be if they used like a hacked launcher, playing minecraft without having bought the game or something. Let me know if you think you can find any defining trait to these players, or a common factor.
These kind of issues are very hard to fix, as there's no real way to find out what happens, but I'd appreciate any information if it would arise

**Comment by rruy-dev** [comment]
The server is an online server (online property enabled in server config, requiring proper UUID authentication through Mojang), with VPN traffic blocked using TCP Shield, and we crack down on hacks pretty heavily and quickly..
The players seem p honest with no abnormally quick progress, actually p slow progress compared to others I.M.O. 
So Idk if that's the case but I'll def do some investigation regarding this.
And try to think of anything else I can investigate that may set the players apart.
Thanks for the quick responses, I'll update you when I get the chance to do this investigation proper.

**Comment by rruy-dev** [comment]
Hi, sorry I took so long to get back to this.

After testing with the affected players, the issue seems to have gone away after the server update to FMC v2.8.0, notably in this version, yigd was updated from v2.0.0-beta.10 to v2.0.0-beta.11.
Thanks for releasing this update! As whatever changes you'd made seems to have resolved this issue.
