### ISSUE TITLE
Very minor issue with Requiem player shell deaths

### ISSUE THREAD

**Issue by AeiouEnigma** [B1n-ry/Youre-in-grave-danger#16]
**Describe the bug**
If a Requiem player's "shell" (basically a stationary Player entity that the player has temporarily departed from controlling) is killed, a grave will be created for it. This grave will use a default Steve or Alex player head and the name "FakePlayer". It would be very nice if a workaround could be devised such that the grave would use the original player's name and head, instead of these defaults.

**To Reproduce**
1. Install YIGD and Requiem.
2. Load up a world.
3. Enter the command `/requiem shell create <your_player_name>` to create a shell of yourself.
4. Give the shell some item so it creates a grave on death.
5. Kill the shell.
6. Observe grave.

**Expected behavior**
The shell player's death should produce a grave identical to what the actual player would have produced on death.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.18.1
 - Version: 1.2.10

**Additional context**
Requiem version 2.0.0-beta.5 was used

**Screenshots**
![image](https://user-images.githubusercontent.com/3160746/147843464-58e5f472-06e3-47d1-927b-1cbf207e2d73.png)

**Comment by B1n-ry** [comment]
I think I can find a way to achieve this. This would however require me to change the grave owner UUID to the actual player, which would result in the same player being able to pick up the grave. I'm not too familiar with requiem so I'm not sure if this is a problem or not. If this wouldn't work I can just add a minor rewrite of the grave owner UUID thing. Wouldn't really be a problem, just not sure how you want this to work. Another solution could be to completely disable graves from requiem shells. But yet again I don't know a lot about requiem so I rather ask someone who knows how things could be affected

**Comment by B1n-ry** [comment]
If it wasn't clear enough, this was a question. I don't know what you want me to do until you reply. I need to know what I need to do to actually do it. Should I make shells not spawn graves? Should I have the player the shell is a clone of being able to open the grave, or should only the shell be able to open the grave?

**Comment by AeiouEnigma** [comment]
Ideally, the shell would spawn a grave that behaves equivalently to how the grave of the player represented by the shell would behave. Shells don't respawn when killed, so the cloned player should be able to open their shell's grave.

**Comment by B1n-ry** [comment]
I can do that. Thanks for answering
I'll make sure it's in the next update

**Comment by AeiouEnigma** [comment]
Thanks very much, and happy new year!

**Comment by B1n-ry** [comment]
Compatibility added in v1.2.11
If you have any other bugs/suggestions, don't hesitate to send them my way!

**Comment by AeiouEnigma** [comment]
It's working flawlessly, thank you!
