### ISSUE TITLE
[QUESTION] How can I remove the tombstone?

### ISSUE THREAD

**Issue by EnderGirl1500** [B1n-ry/Youre-in-grave-danger#165]
Hi there! I want a graves mod for my local world, but I've got a realistic resourcepack and don't want to break the aesthetic. I installed this mod because it says it's highly configurable, so I've been looking for a way of changing the textures of the tombstone or just removing it completely, but I couldn't find one. You can disable the skull, the name, but not the stone.

So yeah, I basically want one of these two options: 1. to be able to choose a texture for the stone or 2. to keep just the skull and the name above it.

Is that possible?

**Comment by B1n-ry** [comment]
You can change the gravestone appearance with resource packs. [Here](https://github.com/B1n-ry/Youre-in-grave-danger/blob/1.20-fabric/src/main/resources/assets/yigd/models/block/grave.json) is how the current grave model looks like, and [here](https://github.com/B1n-ry/Youre-in-grave-danger/wiki/Custom-Grave-Models) is the (slightly outdated) wiki page about how to use the resource pack model file. Note that even if it says it's outdated, it will still work (if I remember correctly). It's just the ground layer name that has changed, and will not get the adaptive rendering if it's enabled when using the wiki names. 
The block hitbox and block entity renderers will change accordingly to how the resource pack is configured. 
Let me know if/if not this is what you're looking for, and if I can be of further assistance

**Comment by B1n-ry** [comment]
Closing the issue, as everything was already implemented for this. Hope you made it work! And if you didn't, you're welcome to ask more questions!
