### ISSUE TITLE
A Player WIth a Grave Glitch

### ISSUE THREAD

**Issue by InfernoCarson** [B1n-ry/Youre-in-grave-danger#168]
so on my server I run one of my players has this glitch where every time he dies, the grave spawns but is instantly classified as destroyed, and when he right clicks it, it doesn't give his items back but it gives his XP back and the grave doesn't despawn, so he can keep clicking it to get levels. He got up to 300 levels one time. Anyone know how I can fix this?

For clarity, this is in Minceraft 1.20.1 fabric modpack that includes Malum, Hephaestus, Simply Swords, and Create. His grave didn't start bugging though until he did a Malum ritual that crashed the serve r5 times, making me get a server side mod just to prevent crashes.

**Comment by B1n-ry** [comment]
Does this server side mod still generate crash logs? It almost seems as if the game would crash, but doesn't since this mod is present

**Comment by Trtrtr70** [comment]
I got the same issue. I also get unlimited XP but can't get my Items back. The chat said that my grave was unexpectedly destroyed and with the permission I can restore the grave with /yigd commands.  

When I go into /yigd moderate I can see my Items but I can't restore or rob them. I just get unlimited XP while clicking on the restore or rob button.

I am playing on Prominence II RPG v3.0.1 which has your Mod YIGD version 2.0.0 beta and is running on 1.20.1 Minecraft. We host the server with BisectHosting.

How do I get my items back ?

**Comment by Trtrtr70** [comment]
> so on my server I run one of my players has this glitch where every time he dies, the grave spawns but is instantly classified as destroyed, and when he right clicks it, it doesn't give his items back but it gives his XP back and the grave doesn't despawn, so he can keep clicking it to get levels. He got up to 300 levels one time. Anyone know how I can fix this?
> 
> For clarity, this is in Minceraft 1.20.1 fabric modpack that includes Malum, Hephaestus, Simply Swords, and Create. His grave didn't start bugging though until he did a Malum ritual that crashed the serve r5 times, making me get a server side mod just to prevent crashes.

Did you manage to get your items back ?

**Comment by B1n-ry** [comment]
If I could read any logs of when this happens, it would likely help me hunt down the bug and fix it

**Comment by B1n-ry** [comment]
I had someone else report a similar issue, could be the same, a few days ago. They managed to solve it by updating the You're in Grave Danger mod. Maybe it will work for you too. If I don't get any answers within like a few days or something I'll just assume it did and close the issue. But please let me know regardless

Here's the other issue report:
https://github.com/B1n-ry/Youre-in-grave-danger/issues/181

**Comment by Trtrtr70** [comment]
It solved it Ty !

B1n_ry ***@***.***> schrieb am Di., 17. Sept. 2024, 17:48:
