### ISSUE TITLE
Cannot run /reload on server as YIGD calls for Client class

### ISSUE THREAD

**Issue by dandin87** [B1n-ry/Youre-in-grave-danger#17]
**Describe the bug**
Cannot run /reload on server as YIGD calls for Client

**To Reproduce**
run /reload from server console

**Expected behavior**
/reload does not fail.

**Desktop (please complete the following information):**
 - OS: [Windows, Linux]
 - Minecraft Version: [1.18.1]
 - Version: [youre-in-grave-danger-1.2.10]

**Additional context**
https://paste.alloffabric.com/izabuducuk.sql

**Comment by B1n-ry** [comment]
I've fixed the problem in the latest push to github. Will be included in the next update. Thanks for reporting! I will close this as soon as I release the update
Should be safe to build the mod from github if you want, or alternatively I can send you the mod jar here (if you ask for it)

**Comment by Shockks** [comment]
im having this error and would love the mod jar if thats ok please

**Comment by B1n-ry** [comment]
Thought I could just attach the jar to these messages but I guess that didn't work so I went ahead and updated the mod. Here's the update on [curseforge](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger/files/3594863). After thinking about it I don't see why I shouldn't update. Sorry you had to wait
