### ISSUE TITLE
Error Retrieving Grave with Modified Trinket Slots

### ISSUE THREAD

**Issue by dainekoichi** [B1n-ry/Youre-in-grave-danger#173]
Hi, I'm having serious issues with this mod, and I think possibly due to Malum's trinket that removes a ring slot and adds 2 rune slots. When I try to retrieve the grave, it clears out my inventory fully and is getting an error in the server (OutOfBoundsException) I've had my friend attempt to rob my grave and the same happened to him. Can you please check it out? Thanks!

Steps to replicate:
- Equip Brooch from Malum with -1 Ring Slot and +2 Rune Slot
- Equip all available rune slots
- Die with the runes equipped
- Go back to grave and attempt to get items back

**Comment by B1n-ry** [comment]
Thanks! I've located the issue, and will release a fix within a few days!

**Comment by B1n-ry** [comment]
Released an update a few hours ago. That should fix your issue
