### ISSUE TITLE
Wrong Version Uploaded For 1.20.1

### ISSUE THREAD

**Issue by Fyoncle** [B1n-ry/Youre-in-grave-danger#174]
![image](https://github.com/user-attachments/assets/51e69ca1-9947-4151-a36e-357ae1bdce28)

**Comment by B1n-ry** [comment]
Omg I'm stupid. This happened last release too, and I thought I fixed it, but turns out I only fixed it on curseforge. 
I've changed the versions of the modrinth upload now anyway. Thanks for letting me know about it

**Comment by Fyoncle** [comment]
> Omg I'm stupid. This happened last release too, and I thought I fixed it, but turns out I only fixed it on curseforge. I've changed the versions of the modrinth upload now anyway. Thanks for letting me know about it

xD You're welcome. ❤️
