### ISSUE TITLE
Configurable item to teleport to last grave location

### ISSUE THREAD

**Issue by Kai-mbe** [B1n-ry/Youre-in-grave-danger#18]
I realize it's a bit out of scope, but a configurable item which allows you to return to your last grave site would be great.

Ideally a relatively high cost to craft by default but achievable in the mid game. A configurable recipe, Xp cost (taken from grave, if possible), and/or configurable debuffs could be a nice way to balance as well.

**Comment by B1n-ry** [comment]
Seems like a cool idea. I already have an idea how it would work. The thing about this that would make it harder to implement would probably be the recipe and item texture. (If you have any ideas of this that you're envisioning, I would appreciate if you could explain/help me, if not I'll probably figure somethig out. Don't feel forced to do anything though. If you haven't given it any more thought that's fine)

**Comment by Kai-mbe** [comment]
As far as I remember, other mods that have added a similar feature have used scrolls as the item. Maybe something like this:
![Annotation 2022-01-13 150505](https://user-images.githubusercontent.com/95777483/149344662-1b003512-4a90-406f-8a20-fee999a4c2c8.jpg)

Gives a reason to have some honey early game, gives a use to phantom membranes and amethyst. Got a bit of a ritual vibe with the candle and crystals. And requires going to the nether first. 

Other items that could fit imo would be: Ghast tear, normal Enderpearl, Crying obsidian (limits the amount you can craft decently), Glow ink, Chorus fruit (but pre-end would probably be better), XP bottle, Potion of slow falling (instead of Membrane)

Something like this maybe? pre nether, but requires venturing deep for amethyst and glow ink. and requires finding a ruined portal while also giving a use to phantom membrane.
![image](https://user-images.githubusercontent.com/95777483/149347566-f093b100-ae5a-4eec-a736-d48da96247db.png)

I'll play around in aseprite a bit and update with a rough sprite.

Scroll Of Returning:
![Scroll Of Returning 300](https://user-images.githubusercontent.com/95777483/149366447-6fe5845b-36bd-42f0-9169-24348f627e74.png)


Alternatively you could have a blank scroll recipe:
![image](https://user-images.githubusercontent.com/95777483/149367602-36eae265-aae6-4f84-9152-b68860fe4d12.png)
 
![image](https://user-images.githubusercontent.com/95777483/149367927-91826734-683d-4f9c-b13f-d9aa9879e88d.png)

Which would allow for expansion if you want to add any more types of scrolls, or different tiers with different debuffs and such.

whipped up a google sheet to play around with the recipes here: https://docs.google.com/spreadsheets/d/1cM_zLzMsqDkFbv7SEz1pkWLAqM_z4ZVOkmVrIz2cKDA/edit?usp=sharing

**Comment by B1n-ry** [comment]
Thank you! I'm sorry if I took a while to respond. Just simply want to let you know that it looks great! I will likely use the scroll texture and some slightly altered recipe. I'll keep the extra features to a minimum however to keep the same kind of customization. This is the kind of system that would be better as a addon mod if I made it detailed enough. So I'll probably just keep it to one item and that's it.
However I highly appreciate you taking the time to make this. It looks awesome!
I'll put this in the next update (whenever that drops... I'm working on a new feature that might take some time to implement)

**Comment by Kai-mbe** [comment]
Awesome! Happy to help realize this feature.

tweaked the scroll sprite a bit, looked off center:
![Scroll Of Returning 160](https://user-images.githubusercontent.com/95777483/149424013-24b51bd0-6138-4d46-85a3-ff2d7e97236f.png)
![Scroll Of Returning 16](https://user-images.githubusercontent.com/95777483/149424016-0b4b7385-68a4-4715-a423-949ef9e5b5a5.png)

And I don't know if you took a look at the sheet so I'll just leave this recipe here:
![image](https://user-images.githubusercontent.com/95777483/149424051-0dd288fd-0812-4523-9f56-67f6f62283e2.png)

It does still seem a bit busy/random but that might be necessary for balance. I feel that Crying Obsidian, even if it looks odd in the recipe, makes it rare enough early game as to not be OP. Although some balance could also come from the nausea, blindness, and bad luck debuffs.

Let me know if you have any ideas for a different sprite or anything,
Cheers

**Comment by B1n-ry** [comment]
Funnily enough a mod just released with this very feature. To be honest it would probably be a good idea just to install that instead. Let me know if you still think I should persue this feature however
[Here](https://www.curseforge.com/minecraft/mc-mods/craftable-utilities) is the download link for this other mod

**Comment by B1n-ry** [comment]
Added in 1.2.12
Gave you credit for the texture in the changelog. So the release on github will now apparently say you're a contributor, and not me lol. Keep in mind that you have to restart the game if you change the config to include this item. And you can easily with a datapack change the recipe if you feel like it's not what you wanted. Enjoy!
