### ISSUE TITLE
render bug

### ISSUE THREAD

**Issue by VaporeonScripts** [B1n-ry/Youre-in-grave-danger#180]
1.21.1, latest neoforge version
![image](https://github.com/user-attachments/assets/e5f8ce33-2f1c-4409-9fbc-5c50307eb32c)

**Comment by B1n-ry** [comment]
Yeah I found this out just the other day. Seems to be some mod incompatibility. I'll see if I can find which one, and if it's possible to fix

**Comment by IMS212** [comment]
This bug is triggered by Sodium, and seems to be caused by the Grave Block Entity not having `hasCustomOutlineRendering` returning true on NeoForge.

**Comment by IMS212** [comment]
Nevermind; I was looking at the wrong branch, I see you have it. Will look into this more.

**Comment by IMS212** [comment]
I have found the bug within Sodium; a fix will be made soon.

**Comment by VaporeonScripts** [comment]
Alright

**Comment by IMS212** [comment]
Fixed in Sodium 0.6 Beta 2.
