### ISSUE TITLE
Issue with latest version on 1.21.1 neoforge

### ISSUE THREAD

**Issue by VaporeonScripts** [B1n-ry/Youre-in-grave-danger#182]
![image](https://github.com/user-attachments/assets/e2a641b4-aca8-4fdd-9699-02e1c0c7b468)

**Comment by VaporeonScripts** [comment]
https://mclo.gs/NoXT8Sc

**Comment by B1n-ry** [comment]
welp that was not intended... I'll find a way to fix it, although it may take a few hours

**Comment by VaporeonScripts** [comment]
alright

**Comment by B1n-ry** [comment]
It did not take a few hours. The fix has just been released on curseforge, modrinth and github

**Comment by VaporeonScripts** [comment]
Alright,ty!
