### ISSUE TITLE
[Suggestion] Cosmetic Armor Reworked compability?

### ISSUE THREAD

**Issue by Zurkie** [B1n-ry/Youre-in-grave-danger#185]
Any possibility to add compability with Cosmetic Armor Reworked mod (https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)? Currently when we die the armor just stays on the ground next to the grave.

**Comment by B1n-ry** [comment]
Yeah definitely! Sort of new to neoforge (or forge) mods so I don't know which mods there are to support very well. Will add compat with Cosmetic armor reworked in the next update though!

**Comment by B1n-ry** [comment]
The mod has now been updated, containing compat with the cosmetic armor mod
