### ISSUE TITLE
Configuration value not taken into account.

### ISSUE THREAD

**Issue by Khytwel** [B1n-ry/Youre-in-grave-danger#19]
The "defaultXpDrop" does not work when this one is on true. It drops only one orb on the ground and the rest is still in the grave.

- Minecraft Version: 1.18.1
- Version: 1.2.11

**Comment by B1n-ry** [comment]
While testing today I found this bug as well (being xp dropped outside the grave). I thought at first this was only due to changes I've not yet implemented in an update but anyhow next update will fix this issue. Will hopefully get time to finish the update in the next 24 hours.
Thanks anyway!

**Comment by Khytwel** [comment]
Thanks to you! :)

**Comment by B1n-ry** [comment]
I updated the mod and made sure that this is in fact not something that will happen anymore. I hope you like the update!

**Comment by Khytwel** [comment]
Thanks! And would it be possible to make an option to drop the xp outside the grave like in Vanilla?

**Comment by B1n-ry** [comment]
Yeah sure I can add that. I can release another update with this feature in maybe a few days. If I find a bug that needs fixing it will be sooner, but it will probably be a max of 3 days or something until the update. Feel free to suggest any other ideas you would like to see in this update or any future update!

**Comment by B1n-ry** [comment]
Updated the mod with the requested feature. By default xp will generate in the grave, but you can change the 
`putXpInGrave` config to change that
