### ISSUE TITLE
Historical Gravestone Information Records

### ISSUE THREAD

**Issue by cathats** [B1n-ry/Youre-in-grave-danger#192]
My friend and I were playing when the server crashed. Before the crash, my friend's items were stored in a gravestone after they died. After the server restarted, the map reverted, and the gravestone disappeared, so the items cannot be retrieved. Is there a backup available, and is it possible to find the gravestone information from the last death?

我和朋友在游玩时服务器崩溃，崩溃前朋友死后东西在墓碑里。服务器重启后地图回档，墓碑消失，现在物品无法找回。请问是否会有备份，可以找到上次死亡的墓碑信息？

**Comment by B1n-ry** [comment]
I don't know how feasible this is for me to fix. Minecraft saves the world data and player data separately, and I don't think if there's anything I can do to fix that. 
Unfortunately if the world data did not update, that most likely means that the grave backup did not save either. If it did, you would access it with the `/yigd grave [user]` command.
Thank you for reporting the problem, and sorry I can't do much to help
