### ISSUE TITLE
Grave don't drop experience on death

### ISSUE THREAD

**Issue by Zano1999** [B1n-ry/Youre-in-grave-danger#2]
**To Reproduce**
1. Kill yourself
2. Retrieve your inventory from the grave

**Expected behavior**
Experience has been restored to the level at the time the mod was installed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.17.1
 - Version: 1.1.2

**Additional context**
A list of my mods:
AllWoolsToStringFabric-1.17.jar
antiqueatlas-6.1.1-fabric-mc1.17.1.jar
appleskin-fabric-mc1.17-2.1.3.jar
architectury-2.6.35.jar
armorhotswap-fabric-1.17-1.3.jar
attachleadstologs-1.0.0-1.17.1.jar
Autofish-0.9.3-fabric-mc1.17.jar
AwesomeDungeonFabric-1.17.1-1.1.1.jar
awokenworld-2.0.0.jar
barren-isles-fabric-1.17-1.0.6.jar
bclib-0.4.0.jar
bedrockify-1.2.0+mc1.17.1.jar
BetterDungeons-Fabric-1.17-1.0.1.jar
betterendsky-2.0.0.jar
BetterMineshafts-Fabric-1.17-1.0.0.jar
bettersafebed-fabric-1.17-1.4.jar
BetterStrongholds-Fabric-1.17-1.0.jar
biome_locator-1.17-1.1.2.jar
branders-sulfurpotassiummod-1.17-1.1.1.jar
c2me-fabric-mc1.17.1-0.2.0+alpha.5.0-all.jar
caelus-fabric-0.0.16-1.17.jar
caracal-1.17-1.3.1.jar
carrier-1.8.0.jar
celib-0.5.0-alpha.jar
chalk-1.0.2.jar
charm-fabric-1.17-3.3.2.jar
charmonium-fabric-1.17-3.3.0.jar
classic-beaches-0.3.1.jar
cleancut-1.17-4.0-fabric.jar
cloth-config-5.0.38-fabric.jar
collective-fabric-1.17.x-1.51.jar
columns-1.2.0.jar
colytra-fabric-2.0.0-1.17.jar
complete-bone-meal-1.2.0.jar
connectiblechains-1.17.1-1.2.3.jar
cpas-2.0.0.jar
curses-mod-1.6.0.jar
CustomSkinLoader_Fabric-14.13-SNAPSHOT-278.jar
darkness-mc117-1.6.72.jar
dehydration-1.2.5.jar
doublejump-1.0.0+mc1.17.jar
DungeonsArise-1.17.1-2.1.48-fabric-beta.jar
earlygame-1.17.x-1.1.1.jar
elytratrinket-fabric-2.0.1-1.17.jar
enderscape-0.1.1.jar
environmentz-1.1.7.jar
explorers-delight-1.0.0-alpha.4.jar
fabric-api-0.42.1+1.17.jar
fabric-language-kotlin-1.6.4+kotlin.1.5.30.jar
fabrication-1.17-2.0.0_01.jar
fallingleaves-1.7.3+1.17.1.jar
FallingTree-1.17.1-2.14.1.jar
flytre_lib-1.17-0.2.14.jar
full-slabs-3.2.1.jar
geckolib-fabric-1.17-3.0.26.jar
grabcraft-litematic-1.17-fabric0.34.9-0.4.jar
grind-enchantments-1.4.0+1.17.1.jar
grizzlybear-1.1.1.jar
guifollowers-fabric_1.17.x-1.7.jar
hookshot-r22.jar
horse-stats-vanilla-4.1.8.jar
illuminations-1.6.3.jar
improved-stations-2.0.5.jar
infinitevillagertrading-1.17-fabric0.34.9-1.1.jar
inventory-hotswap-fabric-1.17-1.2.0.jar
InventoryHUD-fabric-[1.17.x]-3.4.0.jar
inventoryprofilesnext-fabric-1.17-0.7.4.jar
iris-and-sodium-mc1.17-1.1.2+build.9.jar
lambdynamiclights-2.0.2+1.17.jar
lapisreserve-1.0.8.jar
LetSleepingDogsLie-Fabric-1.17.1-1.0.0.jar
litematica-fabric-1.17.0-0.0.0-dev.20210616.033538.jar
lithium-fabric-mc1.17.1-0.7.4.jar
LoudLeads-1.0.1+mc1.17.jar
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1.jar
maptooltip-fabric-1.17-1.3.0.jar
mini-extras-fabric-1.3.2+1.17.1.jar
mobs-attempt-parkour-0.2.3-1.17-pre1.jar
modmanager-1.1.1-alpha+1.17.jar
modmenu-2.0.13.jar
monsters-in-the-closet-1.0.2+1.17.jar
more-geodes-1.0.4.jar
morebannerfeatures-1.0.2.jar
mostructures-1.3.0-pre1-1.17.1-fabric.jar
NE-1.17-Fabric-1.2.0.jar
no-pearl-damage-1.1.0.jar
notenoughcrashes-3.7.0+1.17.1-fabric.jar
noweakattack-1.1.2.jar
observable-0.1.2-1.17-fabric.jar
odysseyhud-fabric-1.17.1-1.0.jar
offhandoverhaul-1.2.0.jar
OldSwing-Fabric-1.17.1-3.0.1.jar
outvoted-1.5.0-b1.jar
paintings-fabric-1.17.1-1.0.0.3.jar
Plated-2.1.1-fabric.jar
quickspyglasser-0.2.1.jar
randombonemealflowers-fabric_1.17.x-1.5.jar
rare-ice-0.3.0.jar
repurposed_structures_fabric-2.5.2+1.17.1.jar
reroll-1.3.0-1.17.1.jar
right-click-clear-2.0.3.jar
rightclickharvest-1.3.0.jar
RoughlyEnoughItems-6.1.314-alpha.jar
scorch-1.2.0.jar
second-chance-1.1.0.jar
shulkerboxtooltip-3.0.2+1.17.1.jar
sihywtcamc-1.3.1+1.17.1.jar
sihywtcamd-1.5+1.17.1.jar
snow-under-trees-fabric-mc1.17.0-1.0.0.jar
Soaring-Structures2-1.17.1-1.9.0-FABRIC.jar
squirrels-1.1.0-1.17.jar
starlight-1.0.0+fabric.73f6d37.jar
stonevaults-1.1.0.jar
strawgolem-1.10-B3.jar
TaxFreeLevels-1.2.jar
terrific-trinkets-1.17.1-0.2.0.jar
torohealth-1.17-fabric-7.jar
totemplus-1.1-1.17.jar
traverse-4.0.0.jar
trinketofundying-fabric-2.0.0-1.17.jar
trinkets-3.0.4.jar
trinketshulkerboxes-fabric-2.0.0-1.17.jar
TrulyTreasures-1.17.1-FABRIC-v1.0.jar
vanilla-hammers-3.1.2-1.17.jar
vanillaexcavators-2.2.0-1.17.jar
wild-update-1.17.1-0.0.7.jar
windchimes-1.2.0.jar
worldedit-mod-7.2.7.jar
wraith-waystones-2.1.2.jar
XaerosWorldMap_1.16.1_Fabric_1.17.1.jar
Xaeros_Minimap_21.15.1_Fabric_1.17.1.jar
xp_storage-1.4+1.17.1.jar
youre-in-grave-danger-1.1.2.jar
YungsApi-1.17-Fabric-16.jar

**Screenshots**
1.
![2021-11-14_23 34 03](https://user-images.githubusercontent.com/42555362/141701454-9ce16585-cae3-4aa1-8993-4bf5825c73e0.png)
2.
![2021-11-14_23 34 19](https://user-images.githubusercontent.com/42555362/141701456-8cd4e513-84bb-4165-ba9d-e7de445e9e3c.png)
3.
![2021-11-14_23 34 39](https://user-images.githubusercontent.com/42555362/141701457-0d6d720c-4da0-43aa-a82c-006733ec9cc0.png)
4.
![2021-11-14_23 34 42](https://user-images.githubusercontent.com/42555362/141701458-74e69ee7-a164-4020-a7c9-3f3e147bea0c.png)

**Comment by B1n-ry** [comment]
Fixed and pushed to 1.1.3
Sorry for taking so long
