### ISSUE TITLE
Origin "keep_inventory" item not kept on death

### ISSUE THREAD

**Issue by Anonymun** [B1n-ry/Youre-in-grave-danger#201]
I did a look around first and saw that there was one other thread about this a long time ago, but it seems the issue requester didn't get back about it working or not before the thread was closed with some kind of fix.
MC Version: 1.20.1
YIGD Version: 2.0.10
I'm using an origin in a datapack that has one item meant to be kept on death. It has NBT data. It works without YIGD, tested using the /kill feature. With this gravestone mod however, the item is tossed into a grave and I have to go grab it. I don't understand what the issue could be since there's origin compatibility, but messing with origin items being kept instead of being put into the grave didn't do anything. If needed I can provide the txt file for the power so it can be checked out.

**Comment by B1n-ry** [comment]
There should be compat in place for entire inventories that should or shouldn't be kept on death, but I didn't know there was rulings about specific items to be kept on death for some powers. I'd be happy to take a look at this origin power and see what I can do to fix this too.

**Comment by Anonymun** [comment]
> There should be compat in place for entire inventories that should or shouldn't be kept on death, but I didn't know there was rulings about specific items to be kept on death for some powers. I'd be happy to take a look at this origin power and see what I can do to fix this too.

Here's the txt file :>
[crafters_thorn.json](https://github.com/user-attachments/files/18275382/crafters_thorn.json)

**Comment by B1n-ry** [comment]
Thank you! I've managed to get it working in my development environment, and it will be included in the next update (should be just a few days away, since I still have other things to fix and implement before I release it)

**Comment by Anonymun** [comment]
> Thank you! I've managed to get it working in my development environment, and it will be included in the next update (should be just a few days away, since I still have other things to fix and implement before I release it)

Thank you so much for the fix! :D I wish you luck with other issues!

**Comment by B1n-ry** [comment]
I've now published the new version, containing the fix
