### ISSUE TITLE
Ghost grave

### ISSUE THREAD

**Issue by Kejse** [B1n-ry/Youre-in-grave-danger#23]
so the problem is that i tried to pickup my grave in the same exact moment it got destroyed by a creeper and now i'm stuck in a position in which i can't open my inventory and i have infinite slowness 
![2022-01-24_20 37 23](https://user-images.githubusercontent.com/95623509/150852365-2617583b-1af3-4d05-b008-980f7d5ffb1b.png)
2

**Comment by B1n-ry** [comment]
You closed the issue so I understand you found a solution?
