### ISSUE TITLE
Dying crashes the game

### ISSUE THREAD

**Issue by nphhpn** [B1n-ry/Youre-in-grave-danger#26]
1. Playing AoF3 with this mod in 1.0.5 version
2. Die

Expected behavior: A grave is placed and the game continue running
Actual behavior: The game crashes

Crash report: [https://pastebin.com/DvC44pJC](https://pastebin.com/DvC44pJC)

This seems to be because the method `getTagsFor` in [this line](https://github.com/B1n-ry/Youre-in-grave-danger/blob/1.16.5/src/main/java/com/b1n_ry/yigd/compat/TrinketsCompat.java#L50) is nonexistent

**Comment by B1n-ry** [comment]
Weird it worked in single player testing...
However the issue should be resolved in 1.0.6 release on curseforge. I'm sorry for all your troubles and I really hope you should be able to play without any interference. Thank you for reporting the issues though!
