### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by BrokenDawn627** [B1n-ry/Youre-in-grave-danger#29]
crash when player die. and the grave was not generated.

**Comment by BrokenDawn627** [comment]
[log.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/8078076/log.txt)

**Comment by B1n-ry** [comment]
Try reinstalling the mod. Something went wrong and the mod can't find a json file. Do you have any datapacks present? This shouldn't change anything I think, but might as well ask

**Comment by B1n-ry** [comment]
Still think the mod didn't get properly downloaded, and something from the download was left out. However this error is sort of no longer possible in the latest version (1.2.19) even if the same thing would happen again
