### ISSUE TITLE
Does not save "Traveller's Backpack" without Trinkets

### ISSUE THREAD

**Issue by Ioandar** [B1n-ry/Youre-in-grave-danger#3]
**Describe the bug**
A somewhat clear description of what the bug is.

**To Reproduce**
1. Have a traveller's backpack on back
2. Die

All is saved but the backpack is gone...

Having the "traveller's backpack" back

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 64bit]
 - Minecraft Version: [java, fabric,1.17.1]
 - Version: [fabric - youre_in_grave_danger_1.1.5]

**Additional context**

**Screenshots**

**Comment by B1n-ry** [comment]
It seems to be working for me. Can you provide any logs and/or which mods you are using?

**Comment by Ioandar** [comment]
Sure, I go lava diving. For Science! :D

Did you wear the travelers backpack?
![2021-11-19_17 01 32](https://user-images.githubusercontent.com/5900479/142653508-b85f073e-c051-4293-afa0-f7716b63d177.png)


Death From Logfile
`
[16:42:31] [Render thread/INFO]: Defaulting world-dependent block state shape to not short: Block{minecraft:lily_of_the_valley}
[16:42:33] [Render thread/INFO]: Defaulting world-dependent block state shape to not short: Block{minecraft:cornflower}
[16:42:34] [Render thread/INFO]: Defaulting world-dependent block state shape to not short: Block{minecraft:pointed_dripstone}[thickness=tip,vertical_direction=up,waterlogged=false]
[16:42:34] [Render thread/INFO]: Defaulting world-dependent block state shape to not short: Block{minecraft:pointed_dripstone}[thickness=tip,vertical_direction=up,waterlogged=true]
[16:43:32] [Render thread/INFO]: [CHAT] Saved screenshot as 2021-11-19_16.43.32.png
[16:44:03] [Render thread/INFO]: [CHAT] Saved screenshot as 2021-11-19_16.44.03.png
[16:44:09] [Server thread/INFO]: Ioandar burned to death
[16:44:09] [Render thread/INFO]: [CHAT] Ioandar burned to death
[16:44:09] [Server thread/INFO]: [STDOUT]: [Yigd] Grave spawned at: 109, 11, -293
[16:44:10] [Render thread/INFO]: [CHAT] Saved screenshot as 2021-11-19_16.44.10.png
[16:44:48] [Render thread/INFO]: [CHAT] Saved screenshot as 2021-11-19_16.44.48.png
[16:44:51] [Render thread/INFO]: [CHAT] Saved screenshot as 2021-11-19_16.44.51.png
[16:45:20] [Render thread/INFO]: [CHAT] Saved screenshot as 2021-11-19_16.45.19.png
[16:45:26] [Server thread/INFO]: Saving and pausing game...
[16:45:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Tommy Test 01]'/minecraft:overworld
[16:45:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Tommy Test 01]'/minecraft:the_nether
[16:45:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Tommy Test 01]'/minecraft:the_end
[16:45:26] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Tommy Test 01]'/appliedenergistics2:spatial_storage
[16:45:29] [Render thread/INFO]: [STDOUT]: Minimap session finalized.
[16:45:29] [Render thread/INFO]: [STDOUT]: Finalizing world map session...
[16:45:29] [Thread-2/INFO]: [STDOUT]: World map force-cleaned!
[16:45:29] [Render thread/INFO]: [STDOUT]: World map session finalized.
[16:45:29] [Server thread/INFO]: Ioandar lost connection: Disconnected
[16:45:29] [Server thread/INFO]: Ioandar left the game
[16:45:29] [Server thread/INFO]: PLAYER_QUIT
`
Normaly the backpack drops itself and writes in chat&log "Backpack dropped at location x,y,z"

But not when I use the grave mod

The pigs :D
![2021-11-19_16 43 32](https://user-images.githubusercontent.com/5900479/142651282-946ca54d-329d-4b84-93ea-2be6aede8188.png)
![2021-11-19_16 44 03](https://user-images.githubusercontent.com/5900479/142651309-6107c771-92ac-4c35-ba06-623421ac5971.png)
![2021-11-19_16 44 10](https://user-images.githubusercontent.com/5900479/142651334-017332dd-25af-404e-8b19-3353dc9e6892.png)
![2021-11-19_16 44 51](https://user-images.githubusercontent.com/5900479/142651363-85d2e0d1-94c6-45ac-938f-4e8cb650e316.png)
![2021-11-19_16 45 19](https://user-images.githubusercontent.com/5900479/142651384-839716cf-b83c-4429-a27d-c2fb06f196a0.png)

Modlist
`
[16:41:50] [main/INFO]: Loading 99 mods:
	- amecsapi 1.1.4+mc21w16a
	- appleskin mc1.17.1-2.2.0
	- appliedenergistics2 9.0.0-beta.2
	- architectury 2.6.35
	- bowinfinityfix rv10
	- cardinal-components-base 3.1.1
	- cardinal-components-entity 3.1.1
	- cardinal-components-item 3.0.1
	- chalk 1.0.2
	- cloth-basic-math 0.6.0
	- cloth-config2 5.1.40
	- clumps 7.0.10
	- coat 1.0.0-beta.9
	- comforts 0.0.7-1.17.1
	- enchantmentdescriptions 4.0.1
	- fabric 0.42.1+1.17
	- fabric-api-base 0.4.0+5847535018
	- fabric-api-lookup-api-v1 1.3.1+5847535018
	- fabric-biome-api-v1 3.2.2+5847535018
	- fabric-blockrenderlayer-v1 1.1.6+5847535018
	- fabric-command-api-v1 1.1.4+5847535018
	- fabric-commands-v0 0.2.3+5847535018
	- fabric-containers-v0 0.1.13+5847535018
	- fabric-content-registries-v0 0.3.1+5847535018
	- fabric-crash-report-info-v1 0.1.6+5847535018
	- fabric-dimensions-v1 2.0.13+5847535018
	- fabric-entity-events-v1 1.3.1+5847535018
	- fabric-events-interaction-v0 0.4.11+5847535018
	- fabric-events-lifecycle-v0 0.2.2+5847535018
	- fabric-game-rule-api-v1 1.0.8+5847535018
	- fabric-item-api-v1 1.2.5+5847535018
	- fabric-item-groups-v0 0.3.1+5847535018
	- fabric-key-binding-api-v1 1.0.5+5847535018
	- fabric-keybindings-v0 0.2.3+5847535018
	- fabric-lifecycle-events-v1 1.4.5+5847535018
	- fabric-loot-tables-v1 1.0.5+5847535018
	- fabric-mining-level-api-v1 1.0.2+6d0fac4218
	- fabric-mining-levels-v0 0.1.5+6d0fac4218
	- fabric-models-v0 0.3.1+5847535018
	- fabric-networking-api-v1 1.0.14+5847535018
	- fabric-networking-blockentity-v0 0.2.12+5847535018
	- fabric-networking-v0 0.3.3+5847535018
	- fabric-object-builder-api-v1 1.10.11+6d0fac4218
	- fabric-object-builders-v0 0.7.5+6d0fac4218
	- fabric-particles-v1 0.2.5+5847535018
	- fabric-registry-sync-v0 0.7.13+5847535018
	- fabric-renderer-api-v1 0.4.5+5847535018
	- fabric-renderer-indigo 0.4.9+5847535018
	- fabric-renderer-registries-v1 3.2.6+6d0fac4218
	- fabric-rendering-data-attachment-v1 0.1.6+5847535018
	- fabric-rendering-fluids-v1 0.2.1+6d0fac4218
	- fabric-rendering-v0 1.1.7+6d0fac4218
	- fabric-rendering-v1 1.10.1+6d0fac4218
	- fabric-resource-loader-v0 0.4.9+5847535018
	- fabric-screen-api-v1 1.0.5+5847535018
	- fabric-screen-handler-api-v1 1.1.9+5847535018
	- fabric-structure-api-v1 1.1.14+5847535018
	- fabric-tag-extensions-v0 1.2.2+5847535018
	- fabric-textures-v0 1.0.7+5847535018
	- fabric-tool-attribute-api-v1 1.3.1+eb76084f18
	- fabric-transfer-api-v1 1.5.1+6d0fac4218
	- fabricloader 0.12.5
	- fallingtree 2.14.3
	- ironchests 1.4.4
	- jankson 3.0.1+j1.2.0
	- java 16
	- libgui 4.2.1+1.17.1
	- libninepatch 1.1.0
	- lightoverlay 6.0.1
	- malilib 0.10.0-dev.26
	- minecraft 1.17.1
	- mousewheelie 1.7.3-newconfig+mc1.17.1-pre1
	- naturescompass 1.17.1-2.0.1-fabric
	- quartzelv 1.2.5
	- reborncore 5.0.11-beta
	- roughlyenoughitems 6.1.331
	- roughlyenoughresources 2.2.0
	- simple_cobblestone_generator 1.1.4
	- somnus 0.0.13-1.17.1
	- team_reborn_energy 2.0.0-beta1
	- techreborn 5.0.11-beta
	- teenycoal 1.0.3-1.16.x-1.17.x-1.18.x
	- travelersbackpack 1.17.1-6.0.0
	- trinkets 3.0.4
	- tweed4_annotated 1.0.0
	- tweed4_base 1.0.0
	- tweed4_data 1.0.0
	- tweed4_data_hjson 1.0.0
	- tweed4_tailor_coat 1.0.0
	- tweed4_tailor_screen 1.0.0
	- wands 2.2.8_mc1.17.1
	- waystones 2.2.1
	- wthit 3.11.2
	- xaerominimap 21.21.0
	- xaeroworldmap 1.18.2
	- xp_storage 1.4.2+1.17.1
	- xp_storage_trinkets 0.1+1.17.1
	- xps 0.2.2.r_for_1.17.x_Fabric
	- yigd 1.1.5
`

**Comment by B1n-ry** [comment]
Sorry for taking so long to reply. I identified the problem, but I do not have a fix in this mod quite yet. I have however a fix for your minecraft world.

The thing you have to do is to set `trinketsIntegration` in your travelers backpack config to true. This will cause your backpack to always go to your trinkets, instead of your inventory. Make sure you do not have the backpack equipped before you do so (in case you don't want to lose more items, or if that's important to you). This will cause the backpack to not be deleted.
As of the mod telling you where the backpack dropped, you can activate the equivalent to the graves in my mods config.

Explanation (you don't have to read this if you don't want to)
I'm not sure that as of now I _can_ fix this in my mod, since travelers backpack doesn't provide (as far as I know) an API for me to use and fetch the data from the player directly. In fact, I couldn't even find the source code for the fabric version of the mod.

**Comment by Ioandar** [comment]
Thank you for looking into it and for your grave mod! It is awesome cool!
cheers

**Comment by Ioandar** [comment]
I followed your lead and so far all looks fine!
Thank you for all your work! closing this now
cheers

**Comment by B1n-ry** [comment]
I didn't intend to close this issue since there still was a problem if you didn't have trinkets installed. Didn't bother to reopen it again though.
Anyways I managed to find a way I could create a optional dependency of the mod, allowing me to access the backpack itemstack equipped on the player on death.

In other words, latest release (1.1.10) should work with trinkets compatibility disabled in the travelers backpack config
