### ISSUE TITLE
Game Crash when Grave expires

### ISSUE THREAD

**Issue by spocane** [B1n-ry/Youre-in-grave-danger#31]
Game Crash when Grave expires when dropping items with XP

**Version**
MC 1.18.1
Fabric API 0.46.4+1.18
Cloth API 3.1.61
You're in Grave Danger 1.2.20

**Changed Settings:**
enableRobbing = false
canDelete = true
afterTime = 10
timeType = "SECONDS"   ***10 Second only for testing purpose, same crash with longer times
dropInventory = true
putXpInGrave = true
xpDropPercent = 100

[crash-2022-03-01_19.45.21-client.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/8166187/crash-2022-03-01_19.45.21-client.txt)

**Comment by B1n-ry** [comment]
Fixed in 1.2.21 and 1.3.0

**Comment by spocane** [comment]
Seems to be working great! Thanks for the quick fix!

**Comment by B1n-ry** [comment]
No problem! I try to fix all bugs and feature request as soon as possible if I find any or get them reported. Just make sure you tell me if anything else unexpected happens with the mod or if you have any suggestions!
