### ISSUE TITLE
/yigd moderate pages dont display proper

### ISSUE THREAD

**Issue by ChristianKilduff** [B1n-ry/Youre-in-grave-danger#32]
![image](https://user-images.githubusercontent.com/51253586/156861922-d7bf2a93-c5ee-4a90-9edb-4f643e1d75b5.png)

looks to me like a simple case of forgetting to set the position y variable to 0 for the new page

**Comment by ChristianKilduff** [comment]
*for next pages it just does not even show

**Comment by B1n-ry** [comment]
Thanks for notifying me. I'll take a look at it within the hour, and probably put out new releases for 1.18.1 and 1.18.2 later today. If you want the update for another version too, lmk

**Comment by B1n-ry** [comment]
Fixed in latest release (1.2.22 for 1.18.1 and 1.3.1 for 1.18.2)
