### ISSUE TITLE
Bug with Inventorio

### ISSUE THREAD

**Issue by GardarikanetS** [B1n-ry/Youre-in-grave-danger#34]
YIGD does not always keep things in inventory.  With some chance things in deep pockets and left hand slots may disappear.
I've done some research, but due to instability I can't guarantee that I've fully covered all cases.
1) soulbound always saves stuff from the 4 starting slots 
 left hand.
2) soulbound always saves stuff from deep pockets and extra 8 left hand slots if soulbound enchantment and deep pockets are applied to pants. however, I think not with 100% chance
3) things from the left hand and deep pockets VERY always saved if the player himself died (crashed for example)
4) if the player killed by a mob, then only with a small chance things can be returned
5)soulbound in the extra slots without pants from point 2-?????

fabric 1.18.1
YIGD 1.2.11
inventorio-1.18-fabric-1.6.2
bug in singleplayer and server

1.3.1 I did not test because inventory was removed from our server.
i'm writing this because i think this has been fixed in the new version of the mod. if you have fixed this bug-please indicate it in the patch note

Translated with www.DeepL.com/

**Comment by B1n-ry** [comment]
I do remember this issue. At some point I experienced it in dev and tried to fix it, which caused it to get even worse in that release. After that I removed the "fix", which made everything work again somehow. 
I can test just in case this is still present, as I think this happened prior to 1.2.11.
For future issues, I would recommend testing with all mods updated, in this case for my mod it's version 1.2.22 (for minecraft 1.18.1). 
However, thanks for reporting this. I can't promise it's still in the game but I will try to rake a look. Imll update you here of what I find out and if I find anything out

**Comment by B1n-ry** [comment]
I've tested it maybe 20 times now, maybe more, by being killed by a mob, which you say most of the time cause items to disappear. I didn't notice this once. I think it's safe to say this is patched, however I don't know if I've included this in some patch notes or change logs. Should be good to just use the latest version
