### ISSUE TITLE
Game Breaking no trace crash

### ISSUE THREAD

**Issue by Laifsyn** [B1n-ry/Youre-in-grave-danger#40]
honestly I don't know what's wrong, but I just spammed /kill command until it didn't let me respawn. and also I could only crash the game(kill task) to exit because it would get stuck on saving world. Something that seems consistent is that it breaks when trying to respawn a 2nd or 3rd time
[yigd config file](https://github.com/B1n-ry/Youre-in-grave-danger/files/8628928/yigd.-.Copy.txt)
here's the export of the modpack with its manifest, configs, and mods with the copy of your mod inside it. There're actually also CT scripts, but I skipped them since I thought that they couldn't have any relationship. If you can't seem to be able to replicate it, then I guess I'll try to send the scripts just in case then.
[Galfar 0.14.4 1.18.2 Fabric-1.0.zip](https://github.com/B1n-ry/Youre-in-grave-danger/files/8628978/Galfar.0.14.4.1.18.2.Fabric-1.0.zip)

I was playing with 4,5GB allocated RAM(I noticed that it capped the RAM capacity when I tried to kill task)

**Comment by Laifsyn** [comment]
Yep. Confirmed. Something in the config is breaking the game. I guess oyu won't need to download the modpack

**Comment by B1n-ry** [comment]
Did you manually spam the kill command or did you let a command block or similar do it for you?

I also understand you tested with only yigd present, with and without altered configs?

**Comment by Laifsyn** [comment]
manually spammed it. Won't take long. just attempting second respawn breaks the game.

I did not test with only yigd as the sole mod though. But with default config the bug disappears

**Comment by Laifsyn** [comment]
at least I could respawn(tested only like 7-8 times. hopefully doesn't break at like maybe 20 or something)

**Comment by B1n-ry** [comment]
Ok I found the problem. When the mod tries to delete a random item when you have no items in your inventory, the mod will forever try to find this item. You can temporarily fix this by resetting the item loss config, and I should have an update by tomorrow with this issue fixed

**Comment by B1n-ry** [comment]
This is now fixed in the newest version for 1.18.1 and 1.18.2
Thanks for reporting in the issue!
