### ISSUE TITLE
Explosions prevent graves from generating

### ISSUE THREAD

**Issue by CapoFantasma97** [B1n-ry/Youre-in-grave-danger#5]
When you die from an explosion (e.g. Creeper) the grave doesn't generate and all of the contents are lost forever.

I tried setting Last Resort to _set_grave_ instead of _drop_items_ in case that'd be the reason (maybe it tried placing the grave after the explosion removes the blocks?) yet it didn't solve the issue. About this, I left _Generate Block Under Grave_ on as default as well as the other related settings.

**System info:**
 - OS: Windows 11
 - Minecraft Version:1.17.1
 - Mod Version: 1.1.6

**Comment by B1n-ry** [comment]
Fixed in 1.1.7
Thanks for reporting!

Also if you would have a similar problem again, you can use the `/retrieve_grave` command
