### ISSUE TITLE
/yigd moderate will not open 

### ISSUE THREAD

**Issue by H077y** [B1n-ry/Youre-in-grave-danger#51]
**Describe the bug**
I cannot open /yigd moderate as it returns an error (Shown below) and haven't been able to for a while

**To Reproduce**
No idea. It happened a few weeks after the server release

**Expected behavior**
To be able to open the menu

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.18.1
 - Version: 1.2.25

**Additional context**
N/A

**Screenshots**
![unknown-12.png](https://user-images.githubusercontent.com/64114013/171059602-125360ed-9386-472e-b50b-37c187f21ea2.png)

**Comment by B1n-ry** [comment]
Is this a large server perhaps? The command will send all the grave data from the server to the client, and I didn't realise there was a limit of how much data could be sent. Right now it looks like there's a lot of data

**Comment by H077y** [comment]
It's not too big. There's 100+ people in the Discord, but I'm not certain how many actually play.
Peak times usually have 10 people online, and I regularly find graves around from people I've never heard of, so perhaps?
Someone recently died and their grave was destroyed by the enderdragon. We tried /yigd restore but they'd already died after so it didn't return the correct grave.

I also believe that there's a lot of graves that haven't been collected by people, though these barely contain any items

**Comment by B1n-ry** [comment]
Well anyhow I will not be able to fix this until about a week from now. 

The player that lost their grave however, this is a bit weird to me (depending on how long ago it was) that the ender dragon could destroy it. I'm not quite sure if this is in the latest 1.18.1 release, but using `/yigd grave [player]`, you can select graves, and press a restore button in the GUI

**Comment by H077y** [comment]
Oh damn that's what I was hoping to do with /yigd moderate. Thanks. No rush, by the way.
It's not the latest update, but it's not too far behind.

**Comment by H077y** [comment]
It will not let me run `/yigd grave [player]`
![image](https://user-images.githubusercontent.com/64114013/171215989-d4252161-d6e0-4ffe-a5df-638a98eb23a6.png)

I can run it on myself, but not the person who died

**Comment by B1n-ry** [comment]
Not quite sure if this is an issue in that version. You have to be an OP, but I guess you know that. If you're not using the latest version, try that. Should only be required to change on the server to work in that case

**Comment by H077y** [comment]
Updating the server to the newest update fixed the `/yigd grave [player]`, thanks

**Comment by B1n-ry** [comment]
A month later, and now with latest 1.18.2 and 1.19 versions you should be able to use the moderate command no matter the amount of backed up graves
