### ISSUE TITLE
crash with newest fabric version

### ISSUE THREAD

**Issue by VBrieden** [B1n-ry/Youre-in-grave-danger#53]
This crashes with fabric-loader-0.14.6-1.18.2
tested with youre-in-grave-danger-1.3.6, fabric-api-0.55.1+1.18.2 and cloth-config-6.2.62

**Comment by B1n-ry** [comment]
Do you have a crash log?

**Comment by VBrieden** [comment]
[crash-2022-06-06_18.08.00-client.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/8848354/crash-2022-06-06_18.08.00-client.txt)

**Comment by B1n-ry** [comment]
It's the same as #46. Delete the config file and you should be good
