### ISSUE TITLE
Requiem - Graves not generated when possessing a non-player

### ISSUE THREAD

**Issue by DarianLStephens** [B1n-ry/Youre-in-grave-danger#56]
**Describe the bug**
When a player is possessing a non-player entity, like a Piglin or Zombie, they don't generate a grave when they die.

**To Reproduce**
1. Install Requiem + YIGD
2. Become Spirit
3. Possess Zombie
4. Die

**Expected behavior**
For there to at least be a config option to generate a grave when possessing these entities.

**Desktop (please complete the following information):**
 - OS: Windows?
 - Minecraft Version: 1.18.2
 - Version: 1.3.6

**Additional context**
We don't treat the graves as some bonus thing that needs penalties or anything, just as a way to keep items from despawning for people who might not be able to get to them in time.
Being able to keep this feature when existing as a different creature would be greatly appreciated.

**Screenshots**
Dying as a human:
![2022-06-15_15 02 54](https://user-images.githubusercontent.com/15375876/173740543-fae51ca9-f2c3-4f15-97e2-b5c719f188c1.png)

Zombie body:
![2022-06-15_15 03 03](https://user-images.githubusercontent.com/15375876/173740562-73f578a5-df43-4611-9ddd-ca7aca61ad3e.png)

Dying as a zombie:
![2022-06-15_15 03 45](https://user-images.githubusercontent.com/15375876/173740591-2cfefd38-106c-4fa4-9008-ca41c2bf1dfc.png)

**Comment by B1n-ry** [comment]
Thank you for bringing this to my attention. I've found a way to fix this, and the solution will be in the next update. Let me know if you find any other bug/missing feature or something else you happen to find

**Comment by B1n-ry** [comment]
Sorry it's taken so long. Just updated the mod. Latest version for 1.18.2 will now have this feature/bugfix
