### ISSUE TITLE
Items Disappeared

### ISSUE THREAD

**Issue by GreenSkull8** [B1n-ry/Youre-in-grave-danger#6]
When going back to overworld from END dimension it deletes all my items.(I am using custom modpack)
When i disable this mod that behavior was gone.

**To Reproduce**
1. Go to end with any item or pick an item there.
2. Click on kill dragon then jump to teleporter.
4. See error.

 Windows 10
 
![All mods](https://user-images.githubusercontent.com/48812315/143289601-1f6b6cde-76f5-4803-ae74-e9ba9ade8882.jpg)
![config](https://user-images.githubusercontent.com/48812315/143289609-f9b8f26d-601c-40dd-bf06-446cb5ec83e0.jpg)

**Comment by B1n-ry** [comment]
I'm sorry this happened to you. I've now fixed this issue in the newest version for 1.17 (and 1.18). These versions are 1.1.8 and 1.1.2. Sorry for taking so long but I've been busy with other things
Thanks for reporting the issue though!
