### ISSUE TITLE
Java Fabric Server Startup shows "Unknown item 'yigd:death_scroll'"

### ISSUE THREAD

**Issue by wolvyreen** [B1n-ry/Youre-in-grave-danger#61]
**Describe the bug**
When starting up the Java Fabric server, I see the following error in the log output.

> [11:46:01] [main/ERROR]: Parsing error loading recipe yigd:death_scroll
> com.google.gson.JsonSyntaxException: Unknown item 'yigd:death_scroll'
>         at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
>         at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
>         at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
>         at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
>         at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:273) ~[server-intermediary.jar:?]
>         at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:260) ~[server-intermediary.jar:?]
>         at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
>         at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
>         at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
>         at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
>         at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
>         at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
>         at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
>         at net.minecraft.class_156.method_43498(class_156.java:954) [server-intermediary.jar:?]
>         at net.minecraft.class_156.method_43499(class_156.java:942) [server-intermediary.jar:?]
>         at net.minecraft.server.Main.main(Main.java:156) [server-intermediary.jar:?]
>         at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
>         at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]

**To Reproduce**
1. Set up a Java Fabric server on Windows
2. Copy the yigd mod to the mods folder
3. Start up the server.
4. Check the log

**Expected behavior**
Error message should not display.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Minecraft Version: 1.19
 - YIGD Version: 1.3.6
 - Fabric Loader Version: 0.14.8

**Additional context**
We run a Java Fabric server on my home network for me and my 3 boys.  Server is not exposed to the internet for security reasons.
As a side note, there are also multiple other mods loaded on the server as well and so I tested this on a brand new clean fabric server without any other mods and the same occurred.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/8437176/176150730-2a077d32-b567-4c4b-b2fd-cbabe7881b1b.png)

**Log output of the server**
[latest.log](https://github.com/B1n-ry/Youre-in-grave-danger/files/8999964/latest.log)

.

**Comment by B1n-ry** [comment]
This error message is expected, since the death scroll item is disabled by default, but can be configured to exist.
Could probably make the warning message not show though for the next update

**Comment by wolvyreen** [comment]
Ah ha!  ok ... alright :-)  
Glad it is something simple then.

**Comment by B1n-ry** [comment]
Error won't now appear in latest versions for 1.18.2 and 1.19
