### ISSUE TITLE
FPS going down when dying after installing this mod

### ISSUE THREAD

**Issue by k2helix** [B1n-ry/Youre-in-grave-danger#64]
**Describe the bug**
My game usually runs at 60 stable fps, but after dying it goes down to 40-50. I've noticed that if I go somewhere far from where I died, the game runs nice again.

**To Reproduce**
1. Die
2. Notice that the fps went down

**Expected behavior**
The game should keep running at 60 fps

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19 Fabric
 - Version: 1.4.1

**Additional context**
The only thing I found in console related to this mod is:
```
[Worker-Main-6/ERROR]: Couldn't load tag yigd:graveyard_structures as it is missing following references: graveyard:small_graveyard (from You're in Grave Danger), graveyard:small_desert_graveyard (from You're in Grave Danger), graveyard:medium_graveyard (from You're in Grave Danger), graveyard:large_graveyard (from You're in Grave Danger)
```

**Comment by B1n-ry** [comment]
I don't know if it could be a render issue.. There is quite a lot of code in the render of the block, but I don't think that alone would slow down your game that much. I have a config for disabling the render however, so I would sugest you try to do that and see if it fixes your issue. Other than that I don't really have anything running on the client that I think could cause any frame drops at all.

The error is just some mod compat I forgot could appear in the logs when the compatible mod is not loaded. Will be removed in next version.
Let me know if you need any help on this or have any other problems

**Comment by k2helix** [comment]
Hi, thanks for your answer.

I should just set useRenderFeatures to false to try without rendering, right? And what features are disabled by doing that (the user head, name...)?

Also if I'm on a server, would this be only client-side or should I also change the server config?

Thanks in advance

**Comment by B1n-ry** [comment]
Yes that is correct. By doing that all render parts are disabled, and the grave will use a static model instead. This is client side only config, as it will only handle what your game looks like.
I should probably add a config for disabling just the grave part of the render as well, without disabling the skull and name rendering on the grave. Anyways this is the only thing I can think of that could hurt your performance when being close to a grave, especially if you're playing on a server

**Comment by k2helix** [comment]
I see, I will check it out disabling the render features, thanks for your suggestions. I'm playing on a server, but it also happens in single player.

**Comment by k2helix** [comment]
Yeah so after disabling rendering in config it works nice. Thank you for making the mod and for your support!

**Comment by B1n-ry** [comment]
Thanks! Glad everything worked out!
Let me know if you encounter anything else that feels out of place/weird or just anything that could be done better
