### ISSUE TITLE
No restore/rob buttons on the GUI of `/yigd grave <player>`

### ISSUE THREAD

**Issue by FederAndInk** [B1n-ry/Youre-in-grave-danger#66]
**Describe the bug**
No restore/rob buttons on the GUI of `/yigd grave <player>` for non OP but still have luckperms set to yigd.*

**To Reproduce**
1. luckperms set to yigd.*
2. not being OP
3. run `/yigd grave <player>`

**Expected behavior**
There should be the restore/rob button for those who have the luckperms permission but are not OP

**Desktop (please complete the following information):**
 - OS: irrelevent
 - Minecraft Version: 1.18.2
 - Version: 1.3.7

**Additional context**

**Screenshots**
![image](https://user-images.githubusercontent.com/24270152/179421295-d95d1ec8-22a5-45e2-bd12-61218034a213.png)

**Comment by B1n-ry** [comment]
This looks like permission api. I should have compat with it, although I have to be honest I have no idea how to use it so it's not tested. Would be thankful if you could tell me how to test this out. Also the mod does not come packaged with permission api so you would currently have to download it from github or play with another mod that includes it to use that feature. Idk why I just made it compatible and not included, but I think I'll change that in the next release

**Comment by deluxghost** [comment]
before displaying UI buttons, player's permission should be considered

looks like only OP is considered

**Comment by B1n-ry** [comment]
So I realized that testing for permission api permissions set on the server doesn't work very well on the client. I've now fixed this and it should now work as you'd expect. New update available at curseforge, modrinth, and github

**Comment by FederAndInk** [comment]
thanks :+1:
