### ISSUE TITLE
Grave did not generate in v1.2.1

### ISSUE THREAD

**Issue by ClaudiusMinimus** [B1n-ry/Youre-in-grave-danger#7]
**Describe the bug**
I am using your mod in my pack, 99 Mods on the Wall: Fabric Edition, which will be published on the 30th with the release of 1.18. In testing today, I was playing in a single-player world and was killed by a mob from [Gobber](https://www.curseforge.com/minecraft/mc-mods/gobber-fabric/files/3531859). When I went to the gravesite there was no grave, and therefore my inventory was gone.

**To Reproduce**
1. Nothing to add but was said above.

**Expected behavior**
Should have been a grave placed with my inventory.

**Desktop (please complete the following information):**
 - OS: Pop OS (Ubuntu 20.04)
 - Minecraft Version: 1.18-Pre7
 - Version: youre-in-grave-danger-1.2.1
 
[latest.log](https://github.com/B1n-ry/Youre-in-grave-danger/files/7599578/latest.log)

[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
dropType = "IN_INVENTORY"
deleteEnchantments = ["minecraft:vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
blacklistBlocks = ["minecraft:bedrock"]
blacklistDimensions = []
graveInVoid = true
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
defaultXpDrop = false
xpDropPercent = 50
renderGraveSkull = true
renderGraveOwner = true
adaptRenderer = false
tellDeathPos = true

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "minecraft:cobblestone"
inNether = "minecraft:soul_soil"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"
whiteListBlocks = ["minecraft:air", "minecraft:water", "minecraft:lava"]
[utilitySettings]
soulboundEnchant = true

Thank you,
CM

**Comment by B1n-ry** [comment]
I can't seem to replicate this issue... I did find however that I forgot some things while implementing the 1.18 pre release update, where the world height changed. Hence why the grave didn't want to generate the grave at y=-3. There's also a tiny bug where "tell death pos" will only tell you where you died (will fix this in the next update as well), and told you a different location than what showed up in your logs, which is the same location but y=4 instead. Can you please check if the grave is there?
Thank you

**Comment by ClaudiusMinimus** [comment]
I had to dig to find it, but it was there exactly where you said it would be. 
Thank you and I look forward to the next update.

**Comment by B1n-ry** [comment]
New version with these features are now in the newest version of the mod for 1.18 (and 1.17). (versions 1.1.8 and 1.2.2)
Thank you for using my mod!
