### ISSUE TITLE
[1.18.2] Grave not generating above ground

### ISSUE THREAD

**Issue by itsdinkd** [B1n-ry/Youre-in-grave-danger#70]
Suffocating in walls will not create the grave above ground, it will generate it where you suffocated. there should be a setting that allows you toggle if you want the grave to generate on the first closest block on the Y axis above ground or to generate where the death occurred if they suffocated. 

YIGD version 1.3.7 
1.18.2
![image](https://user-images.githubusercontent.com/35115304/181065779-a7897c05-abf9-4c1e-a24c-2f6b5840ea9e.png)
(I broke the blocks but as you see, the grave is on the bottom where I suffocated)

**Comment by B1n-ry** [comment]
You can enable the `trySoft` config, which will place the grave on a nearby block that is either air, water, or any obstructive blocks like grass or snow. This is of course if any blocks like these are actually found nearby. There is no "same coordinates but different Y level" config, but I can take a look at implementing that as an option

**Comment by B1n-ry** [comment]
I've added a config called `trySoftApproach` that can let you configure how the `trySoft` config thing works. By default it's radius, working out from a block in all directions, but you can also configure it to work up and down in y level only, or alternatively only up from where you died.
Thank you for the feature request/issue/bug report! Let me know if there's anything else you would like to see in the mod!
Newest versions for 1.18.2 and 1.19.2 is out on curseforge, modrinth, and github

**Comment by itsdinkd** [comment]
Thank you, i'll give it a try!

**Comment by itsdinkd** [comment]
btw; could there be any issues for having trySoft, tryHard, and this new try setting enabled?

**Comment by B1n-ry** [comment]
No they should all work together. The reason I made a new config is because else configs would break when updating, and suddenly there's a boolean where there should be text. The `trySoftApproach` is just an extension of the `trySoft` config. If this one were to fail, `tryStrict` will take effect, if that is enabled. With `trySoft` enabled, the `tryStrict` config is just a very unlikely backup solution, but at least it's there
