### ISSUE TITLE
Make graves optionally persistent

### ISSUE THREAD

**Issue by Grumpey102** [B1n-ry/Youre-in-grave-danger#73]
Hey!

**Is your feature request related to a problem or do you just have an idea that fit the theme of the mod? Please describe.**
I have an idea that would fit the theme of the mod. I would like if there was an option to let the grave stay, after I got the items out of it, because it would be interesting to see grave markers of your previous deaths. 

**Describe the solution you'd like**
In Terraria it's always a little nostalgic, when you find earlier grave markers, so I'd like if the grave wouldn't just be a temporary chest with items and XP, but an actual marker with the player head and a description "Grumpey died here". Maybe an option called "persistant graves", with a tooltip "When enabled, graves stay after reclaiming them, to remind wanderers of previous deaths". You'd still be able to manually remove it with a pickaxe or something.
The text could also be customized with the option to include the minecraft day / time or reallife day / time (or both). I don't know how hard it is to program that, but in Terraria the grave also says what killed you (Grumpey was crushed by a falling boulder). So maybe also include it, too? "Grumpey was killed by a phantom on day 2 (July 29, 2022, 11:15PM)"

It would also be great if that text would stay if you remove the gravestone, so you could collect your deaths somewhere and create a graveyard.

**Describe alternatives you've considered**
Alternatively you could let us place graves with our head and let us rename maybe by sneaking + right click, so we can name the graves ourselves while we're not near an anvil.

Greetings,
Grumpey

**Comment by B1n-ry** [comment]
Yeah this idea sounds great! I'll try and see how well I can do this, but there shouldn't be any problem. Currently you can craft your own grave, rename it in an anvil, and right-click with your head on it to put it on the grave. The death message should already be stored with the graves so all I need to do then is to store the time/minecraft day (I'm leaning more towards minecraft day but there's no reason not to store both). 
I'll see how easy it'll be to make the grave retain the nbt when broken like you want, but I'm sure it's not too difficult. I'll do my best to create this feature in the mod. Thanks for the suggestion!

**Comment by B1n-ry** [comment]
Just updated the mod on curseforge, modrinth, and github, and this is what I did:
I added the `persistGraves` config. At the moment that's the only config related to this feature, and there's no way of configuring this more specificly. Enabling the `persistGraves` config will make graves stay when you claim them. When you right click on the graves after this they will send your death message and tell you which minecraft day you died on. You can then mine the grave with silk touch to get the grave as an item with all the info still on it. Using anything else will only drop the grave block. So you can then move the grave around and place it somewhere memorable, or whatever you would want to do with it.
It's a pretty cool idea! Thanks for suggesting it! Let me know if you have any other ideas of things I could implement in the mod, and I can take a look at it!
