### ISSUE TITLE
Check Trinkets drop rule (Item Dupe)

### ISSUE THREAD

**Issue by jakeb072001** [B1n-ry/Youre-in-grave-danger#75]
Hi, seems that my mod TerraMine may have some issues with this mod where my items duplicate.
As far as I can tell this Is because my trinket slots are set to keep their inventory, so I assume they are being added to the grave and kept in inventory.
Best way to fix this is to check the drop rule for the trinket slots.
[Trinkets code may help with this (dropInventory)](https://github.com/emilyploszaj/trinkets/blob/main/src/main/java/dev/emi/trinkets/mixin/LivingEntityMixin.java),  this can also add support for the delete drop rule which just deletes the trinkets and shouldn't put them in a grave or drop them.

**Comment by B1n-ry** [comment]
I have to be honest, I saw that trinkets had a drop rule quite some time ago, but I had completely forgotten about it. I'll do my best to implement this in the mod. Thanks for pointing it out!

**Comment by B1n-ry** [comment]
I'm sorry for this taking so long. I've had to wait for some other mods to update, but now they have updated and I can work on the mod again. I've written a simple implementation but for the time being I can't seem to find which items/slots to test the feature on/with. Could you help me in saying how I should test this? (what items to use for example)

**Comment by jakeb072001** [comment]
I quickly made a test mod you can use that has one of each drop rule, it also includes a trinket you can equip into these slots. The item is just called Example Trinket. The duplication was reported to me by someone else but I don't get the duplication myself, however the items do still get added to the grave when they shouldn't.

[example-trinkets-1.0.zip](https://github.com/B1n-ry/Youre-in-grave-danger/files/9490248/example-trinkets-1.0.zip)

The jar is in the zip btw.

**Comment by B1n-ry** [comment]
Thanks a bunch! My implementation seemed to work, and I've now pushed an update to github, curseforge and modrinth. Really like your mod btw. Always cool to see things from terraria in minecraft, but especially stuff like corruption! Keep up the good work, and thanks again for the help!
