### ISSUE TITLE
Grave items don't stack with non-grave items

### ISSUE THREAD

**Issue by DolarJoe** [B1n-ry/Youre-in-grave-danger#77]
**Describe the bug**
Grave items don't stack with non-grave items

**To Reproduce**
1. pick up an item (birch log)
2. use `/kill` command (or any other means to kill the player)
3. pick up the same item
4. pick up the grave 

**Expected behavior**
I have a stack of 2 birch logs in 1 inventory slot

**Actual behavior**
I have 2 slots in inventory each with 1 birch log. After dropping them on the ground and picking it back up the issue fixes itself.

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft Version: 1.19.2
 - Version: 1.4.3

**Additional context**
- No other mods are installed, purely a yigd issue.
- See screenshot for the difference in NBT data

**Screenshots**
![2022-09-14_11 59 39](https://user-images.githubusercontent.com/84009463/190124655-98d0a89d-6006-4007-b4d4-ae3b8c96c9da.png)

**Comment by B1n-ry** [comment]
Huh that's odd... I was aware of that it would split the items in different stacks but not that it couldn't stack at all after. I'll try and see why this is caused and what I could do to fix it. I'll let you know when I release a new version with the fix

**Comment by B1n-ry** [comment]
Released a new version (1.4.4) that will fix this. Thanks for reporting the issue!
