### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by AnomalousDeity** [B1n-ry/Youre-in-grave-danger#78]
**Is your feature request related to a problem or do you just have an idea that fit the theme of the mod? Please describe.**
No not a problem but a cool idea for Graves/graveyards 

**Describe the solution you'd like**
I was hoping to see like maybe a rare chance a Zombie with the player head is spawned from your grave or when opened

**Describe alternatives you've considered**
just by rare chance or on opening the grave
**Additional context**
gotta keep my server on their toes so figured a zombie rising out of their graves would do and also Fit the theme of you are in grave danger :)

**Comment by B1n-ry** [comment]
Sorry for not replying to your issue. I usually try to, but at the time you created the feature suggestion, I was busy and didn't have the time to tend to this mod. I've slowly tried increasing productivity on this project as well as other projects, and I've implemented a config allowing you to do this very thing.
The config is called `randomSpawnSettings` and can vastly controll entities spawned when retrieving items. You can configure the chance of an entity spawning, what type of mob it should be, and what NBT data it should contain. In the NBT data you can use values as grave owner UUID, grave owner username, grave looter name and UUID, as well as every item in the inventory of the grave owner. You can alos decide if using the item in the NBT should be removed from the grave drops or not (in case you would like to spawn a zombie with all the stuff, making you have to fight for it back for example).
I realize that the current default config, even though it's supposed to work like you asked (zombie with player head), it will not do that. You have to replace the NBT data with this for it to work: `{ArmorItems:[{},{},{},{id:"minecraft:player_head",tag:{SkullOwner:{Name:"${owner.name}",Id:"${owner.uuid}"}},Count:1b}]}`

This was probably more than you expected. And someone else asked about a similar feature (with another entity type), so I decided to just make it as configurable as I possibly could. Let me know if you have any questions, or if you would like me to create a config setting for your need.

This feature is in the latest version for minecraft 1.18.2 and 1.19.2
