### ISSUE TITLE
[Quilt 1.18.2] Recipe for death scroll isn't working

### ISSUE THREAD

**Issue by faeldray** [B1n-ry/Youre-in-grave-danger#79]
**Describe the bug**
The recipe for a death scroll exists, but the output is empty. The scroll is enabled (`scrollType = "SCROLL_OF_RETURN"`) so that's not the issue.

**To Reproduce**
1. Enable the scroll in the config
2. Look up the recipe in REI or attempt to craft it.

**Expected behavior**
Death scroll recipe produces a death scroll

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version: 1.18.2
 - Version: 1.3.10

**Additional context**
Quilt Loader: 0.17.5-beta.2

Other mods:
Architectury 4.9.84
Cloth Config 6.3.81
QFAPI 1.0.0-beta.24 and QSL 1.1.0-beta.26
REI 8.3.529

**Screenshots**
![image](https://user-images.githubusercontent.com/967709/191637394-64d6d669-089a-4dad-8b48-d5eb24005a29.png)

**Comment by B1n-ry** [comment]
Sorry for not replying, I've seen the issue and to be fair it's just me forgetting the recipe should exist when the item is enabled in configs. Anyway, I just released an update with a fix for this for minecraft 1.18.2 and 1.19.2. I don't know if it works with quilt as I specifically develop for fabric, but this was a fabric issue too, and should now be fixed. Thanks for reporting!

**Comment by faeldray** [comment]
It works on Quilt as well now, thank you!
