### ISSUE TITLE
Grave Compass not properly named

### ISSUE THREAD

**Issue by RUTHINAS** [B1n-ry/Youre-in-grave-danger#81]
**Describe the bug**
Grave Compass is not properly named in game. Grave Compass settings tab is not properly named in config screen (ModMenu)

**To Reproduce**
1. Browse Mod Menu to YIGD settings
2. Open Utility Settings panel
3. Scroll down and find "text.autoconfig.yigd.option.utilitySettings.graveCompassSettings" panel, open it [bugged name and tooltip]
4. Set "Receive on death" to true
5. Die
6. Mouse over the newly received compass. It is named "item.yigd.grave_compass" [bugged name]

**Expected behavior**
The item name is expected to appear like any other item, for example Grave Compass or a localized alternative (if available).

The config title and tooltip are expected to appear like the other texts in the config menu, for example Grave Compass Settings and a tooltip briefly explaining the functionality of the compass.

**Desktop:**
 - OS: MacOS
 - Minecraft Version: 1.18.2
 - Version: 1.3.10 for 1.18.2

**Screenshots**
![item](https://user-images.githubusercontent.com/94254826/193630795-a43da18a-d646-45bd-8d26-080ce1194e49.png)
![modmenu](https://user-images.githubusercontent.com/94254826/193630799-c6f53686-2152-4de6-9277-e71ed0125929.png)

**Comment by B1n-ry** [comment]
Oh yeah that config translation I just completely forgot about. The item worked for me in dev environment, but I guess I must have added some mod or something that changes that. I'll take a look at it

EDIT: I found the issue with the item and it seems like it's some typo I made some time ago. Will be fixed in the next update

**Comment by B1n-ry** [comment]
Fixed in latest versions of the mod for 1.18.2 and 1.19.2. Sorry this took like a month. I usually try to fix things faster but lately I've had less time to do modding, which is affecting the time spent on this project
