### ISSUE TITLE
Moderate Panel Huge Lag and cause memory heap crash

### ISSUE THREAD

**Issue by bugescape** [B1n-ry/Youre-in-grave-danger#83]
**Describe the bug**
It's dumb that when you /yigd moderate, click "claimed" and "destroyed", it trying to load every single items in all grave history and also trying to load every single player heads in the server. I don't need to load everything just from the moderate page, please just give me a list of all the player names, and then when i click into the player's grave, that's when you start to load all the items in a grave.

If you code it so you load everything on the moderate page this makes moderation on a large server literally unusable

**To Reproduce**
/yigd moderate
on a large server with 20 active players and 500+ player data stored
huge lag and game freeze when trying to load "claimed" and "destroyed" graves, game will some time crashed or server boot you out due to java memory heap too big

**Expected behavior**
only load player name when you moderate, not even loading any player heads, not loading any grave contents

**Desktop (please complete the following information):**
windows, fabric, 1.19.2

**Additional context**

**Screenshots**

**Comment by B1n-ry** [comment]
Oh... yeah I see this becoming an issue now. A while back someone had issues when putting all players in one packet, that the packet grew too large, so I made it send one packet for each grave. Didn't think much more about it at the time but it would make sense that the server can't handle that many packets being sent. I'll try to change the packet system again, hopefully for the last time, to be both efficient AND scalable. 
Thank you for the report, I'll let you know once I publish a new update

**Comment by B1n-ry** [comment]
Alright it's been some time, but now I've updated the mod with a more "big server" friendly packet networking system. Let me know if there's any weird behaviour with this if you find anything. Also let me know if there's anything else you want me to do with the mod. 
I'm sorry for the long wait but I've had school and other stuff that's just taken a lot of my time. Thanks for reporting this in though! Appreciate it!
