### ISSUE TITLE
Dying in a Create crushing wheel causes softlock crashing

### ISSUE THREAD

**Issue by pllot** [B1n-ry/Youre-in-grave-danger#87]
The crash seems to occur when Create mod attempts to crush the gravestone.

1. Set up crushing wheels
2. Fall in and die

**Expected behavior**
Game should not crash

 - OS: Windows
 - Minecraft Version: 1.18.2
 - Version: Fabric, 1.3.11

**Additional context**
Can use another application to delete the grave, so you can load in to your world again. It became a generic grave when I tried to move it, but '/yigd restore' works to restore items.

This may be more of a compatibility thing for create to deal with but I figured I would leave this here, as well as ask if there's something I can do to prevent this from crashing my world again.

**Comment by B1n-ry** [comment]
Do you have a crash log?

**Comment by pllot** [comment]
[crash-2022-11-15_23.57.02-client.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/10060633/crash-2022-11-15_23.57.02-client.txt)
[crash-2022-11-15_23.51.53-client.txt](https://github.com/B1n-ry/Youre-in-grave-danger/files/10060634/crash-2022-11-15_23.51.53-client.txt)

51 is the first crash, 57 was relaunch

**Comment by B1n-ry** [comment]
Lol I actually think this is for some reason inventory tabs. I've had this reported before but I have no idea where it comes from or why it's thrown. Mighgt look into it at some point if inventory tabs doesn't fix it

**Comment by pllot** [comment]
Ah okay. I had crashed before from that mod by opening inventory next to a grave, but I just made a mental note to not do that again

**Comment by B1n-ry** [comment]
Alright figured it out. So inventory tabs tries to add all block entities as inventory tabs, including graves. The mod dev of inventory tabs actually thought of this and added a tag for mod devs to add block entities to that should not be used when generating the tabs. 
In other words I've managed to fix this on my end. I'll update the mod in a few days. In the meantime you can add graves to the inventory tabs exclude config if you want to, but I'll let you know as soon as I update

**Comment by B1n-ry** [comment]
Alright I've updated the mod and now the game should no longer crash when you die, and when using both inventory tabs and yigd. Thanks for reporting this!
