### ISSUE TITLE
Compatibility with 1.19.3? Any time soon?

### ISSUE THREAD

**Issue by wolvyreen** [B1n-ry/Youre-in-grave-danger#96]
Just wondering if there will be a release soon as we love this mod so much and feel it is an essential mod we can't live without.

**Describe the bug**
Game crashes with 1.19.3 when using 1.19.2 obviously as it is not compatible.

**To Reproduce**
1. Install latest version of mod (1.19.2). I know there is no 1.19.3.
2. Start game
3. Game Crashes with Exit Code: -1

**Expected behavior**
Game should not crash and mod should work

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: 1.19.3
 - Version: 1.19.2

**Additional context**
Crash Error that is produced:
```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yigd'!
```

**Comment by B1n-ry** [comment]
I'll try to get a 1.19.3 release up this weekend. The 1.19.3 release is done, I just want to fix up some bugs and drop it together with 1.18.2 and 1.19.2 updated versions (with bugfixes and such)

**Comment by B1n-ry** [comment]
The mod has now been updated. Thank you for your patience!

**Comment by wolvyreen** [comment]
You're a superstar!!  Thank you so much!!
