### ISSUE TITLE
Grave contents deleted after world reload

### ISSUE THREAD

**Issue by lolman9998** [B1n-ry/Youre-in-grave-danger#98]
**Describe the bug**
Upon game crash, all grave contents got deleted.

**To Reproduce**
1. Die
2. Crash game after respawning but before game saves/you get your items back
3. Reload world and attempt to reclaim items
4. Grave will not respond to it

**Expected behavior**
To get my items back

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Minecraft Version:1.19.3
 - Version: 1.5.0

**Comment by B1n-ry** [comment]
I'm aware of this, and it's actually worse than this. It's every time you relogg (and maybe go to an unloaded dimension. It's not confirmed, but could be the case). I have a fix ready to upload, I'm just waiting for one more response at another issue. Do note however that you can still reclaim your items with `/yigd` commands

**Comment by lolman9998** [comment]
Got it. Ill update this mod once you release that change. Will use those commands for now though. Thanks for the help.

**Comment by B1n-ry** [comment]
Released an update earlier today with a fix. Let me know if there's anything else that needs fixing or could use with an improvement. Thank you for reporting!
